### ISSUE TITLE
Big lag of compilation and display

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#3640] opened 2024-05-13 15:18 UTC
### Environment
- TeXstudio: 4.8.0
- Qt: 6.4.1
- OS: Linux Mageia 9
- TeX distribution: TeX Live

### Expected behavior
No lag

### Actual behavior
Compared to TXS 4.7.2, there is a quite big lag, at least with some documents, both for the compilation and for the PDF to be displayed in the (windowed) PDF viewer (see joined screencast). The only difference I see with documents that compiles as quickly as expected, is that e.g. the one on the screencast is a `git` versioned one.

https://github.com/texstudio-org/texstudio/assets/1032633/f97ed2c5-6b3b-41c8-a209-2e417c397818

**Comment by sunderme** [comment] 2024-05-13 16:34
I am not aware of changes on build system/pdf viewer ..
and I don't really notice them here, but I also don't compile often.

**Comment by dbitouze** [comment] 2024-05-13 17:31
Experiences:

- I compiled the file from the CLI and there is no lag (0.49s user 0.13s system 99% cpu 0.624 total).
- I've moved the `.git` repository elsewhere so that the file is no longer `git` versioned and the lag with TXS persists.
- I moved the file from the very deep `~/latex/enseignement/latex/courses/annexes` folder to `~/` (my `HOME`) and there is no lag with TXS.

**Comment by sunderme** [comment] 2024-06-15 13:24
can't reproduce (ubuntu 22.04 with `~/Dokumente/tex/test_dir/level1/level2/level3/level4`)

This seems very specific to the concrete system (qt version, file system, linux kernel)
Unless there is some more concrete pointer what needs to be adapted, I close this.

**Closed by sunderme** 2024-06-15 13:24 UTC
