### ISSUE TITLE
Home key when on first line of indented paragraph

### ISSUE THREAD

**Issue by cohensm52** [texstudio-org/texstudio#3172] opened 2023-06-22 01:44 UTC
I just updated to texstudio version 4.5.2 (and also just updated miktex). Now the Home key is acting differently than it used to, and this is (for me) undesirable. I'm using Windows 10 and Miktex 2.9.

### Describe the feature and the current behavior/state
If the cursor is on the first line of a paragraph, the Home button now takes it to the left-most position of that line, even if the line starts with a tab character, so that the entire paragraph is indented. I'd like it to move the cursor to a point just to the left of the first "letter" character, which would be to the right of that tab character, which I'm pretty sure is what it used to do. If the cursor is on any line other than the first in the paragraph, the Home button does what I want it to do. For example,

     some text
    ^move cursor to here
^rather than to here
Hopefully that's clear what I'm asking. I'm not sure how to get the "^rather than to here" to go inside that grayed box.
### Who will benefit with this feature?
I'd guess everyone?

**Comment by cohensm52** [comment] 2023-06-22 16:24
Thank you, that’s a better way to show what I mean.
When I hit Home once, the cursor moves from
    abc   def |
to
|   abc   def
It only does this if the cursor is on the first line of the indented paragraph. I would like it to go to
    |abc   def



________________________________

**Comment by octaeder** [comment] 2023-06-22 16:42
you reverted smart home as discussed with you in #3171? That's important to know for @sunderme , right?

**Comment by cohensm52** [comment] 2023-06-22 16:49
As pointed out by @octaefer, I should mention that I already reverted smart home as discussed in #3171<https://github.com/texstudio-org/texstudio/issues/3171>?

________________________________

**Comment by sunderme** [comment] 2023-06-22 17:00
Sounds like you actually want the smart home functionality ?

**Comment by octaeder** [comment] 2023-06-22 17:05
I think he wants following: when the line starts with tabs then the cursor should jump to the position after last of those tabs. And that's the only position he wants with home key.
Not sure what it should be when the line is indented by blanks. I assume it should be position 0 then.

**Comment by cohensm52** [comment] 2023-06-22 17:08
Yes, @***@***.***> is correct, that’s what I want. Except, I don’t know what blanks are, are they just spaces?
________________________________

**Comment by octaeder** [comment] 2023-06-22 17:13
yes. there is an option in txs that can insert a given number of spaces (say 4) when you press tab. so should the behavior be the same regardless of the type of empty space the line begins with?
![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/62a44c99-182a-44b7-b98f-e42a6cd333af)

**Comment by cohensm52** [comment] 2023-06-22 17:39
Having not previously known about that option, I’ve only ever used the tab key to insert actual tabs. So, I guess I don’t have an opinion on that question.
________________________________

**Comment by octaeder** [comment] 2023-06-22 17:43
well, I would suggest same cursor movement regardless of whether they are spaces or tabs.

**Comment by cohensm52** [comment] 2023-06-22 17:56
I think that makes sense. I guess I agree with @***@***.***>, same cursor movement regardless
________________________________

**Comment by sunderme** [comment] 2023-06-22 19:04
I still don't see the point. It acts the same.
"Start of line" (old behavior) always skips any blanks and jumps to column 0.
"Start of text" jumps to the first character (if indented by space or tab)

**Comment by octaeder** [comment] 2023-06-22 19:10
besides the fact that I can' t reproduce the strange behavior regarding line 0 stated above, assigning home key to "start to text" results in smart home. I think that the user wants that the jump to first character happens independently of how often you press home, so cursor should never jump to pos 0 as long as there are tabs or spaces at the beginning. Hopefully user clarifies this.

**Comment by cohensm52** [comment] 2023-06-22 19:29
No, actually, that's not what I'm saying. I was going to include screen shots of what I want, but the behavior of my Home keep has changed since yesterday, so I think this needs to be addressed first. Everything I say below is with reference to an indented paragraph. 

Yesterday: after implementing the fix suggested in #3171 by @octaeder, the Home key took the cursor to the start of the current line, and just to the left of the first "letter character", if that line was NOT the first line of an indented paragraph. On the other hand, if the cursor was in the first line of that paragraph, then Home took the cursor to the left of the tabs, which means it went to the furthest left it is possible to go. 

Today: The behavior is back to what it was before I did the fix of #3171, and the mapping has reset itself to what it was before I did that fix. That is, no matter which line of the paragraph the cursor is on, Home takes the cursor to the start (first line) of the paragraph, and to the right of the tabs. In addition, the fix @octaeder suggested yesterday appears to no longer be possible. The Basic Key Mapping has "Move cursor to first character in line" mapped to Home, and "Move cursor to line start" mapped to "none". When I try to change the latter ("none") to Home, there is no longer a "Home" option.

**Comment by octaeder** [comment] 2023-06-22 19:32
> If the cursor is on any line other than the first in the paragraph, the Home button does what I want it to do. For example,

@cohensm52 I guess that the situation you see is like this:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/3a936f60-8a7a-4cff-aebd-2a02c2630b2a)

But this is only one line of the editor (s. line number) that is folded to fit the line width. In this case home jumps in any of these folded lines from the end to start of text, except the first line. What happens in the first line depends on whether you have assigned home to "jump to start of line" or to "jump to start of text" (smart home).

After changing shortcuts reopen config to check if it is as intended.

**Comment by cohensm52** [comment] 2023-06-22 19:43
OK, ignore (most of) my last comment, I guess one can just type "Home" in for the key mapping. So, I can change it back to what it was yesterday with the fix of #3171, but does anyone know why it reset to what it was before I did that fix?

Also, I was going to use the Print Screen key and then paste it in here to demonstrate what I'm saying, but it would probably be better if I knew how to get the screenshots like the one @octaeder posted in his last comment. How do I do that?

Yes, @octaeder, that is the kind of thing I see. I don't see options for "jump to start of line" or "jump to start of text". Just "Move cursor to first character in line" or "Move cursor to line start".

**Comment by cohensm52** [comment] 2023-06-22 20:40
@sunderme Starting from here: 
![image](https://github.com/texstudio-org/texstudio/assets/79482316/a54205b0-420d-4b4c-b491-65d9a77b83c4)
pressing Home goes to here:
![image](https://github.com/texstudio-org/texstudio/assets/79482316/63575b82-182e-4ac6-8ff1-cea4afe3df32)
This is after the fix of #3171 .
On the other hand, starting from here: 
![image](https://github.com/texstudio-org/texstudio/assets/79482316/d3302e01-3c20-46b2-838a-db5b67b6b86a)
pressing Home goes to here: 
![image](https://github.com/texstudio-org/texstudio/assets/79482316/4ba5cba7-d3f9-43b2-96a7-0aaf42d0583a)
whereas I would like it to go to here:
![image](https://github.com/texstudio-org/texstudio/assets/79482316/51b3fbdb-6ea1-4b4f-8e4d-997d6fb8bc14)

**Comment by octaeder** [comment] 2023-06-22 20:50
that's what I said. If you use smart home is only noticeable in the first part of the folded line. With smart home you would exactly get what you wanted: The cursor would move to first character (that is not a space) in line. When you continue pressing home: Jump between line start and first character of line. I think this is what you need. So you shouldn't revert smart home.

**Comment by cohensm52** [comment] 2023-06-22 20:58
I'm not sure what Smart Home is. Are you saying TexStudio already has that capability, or are you suggesting it as a new feature? If the former, I don't see how to set it up.

**Comment by octaeder** [comment] 2023-06-22 21:08
The new behavior of the home key since 4.5.2 is called smart home (s. #3012). You used above image to interchange the settings as I mentioned [here](https://github.com/texstudio-org/texstudio/issues/3171#issuecomment-1600277875) to revert/disable this new feature. If you want to activate smart home again (i.e. default behavior in 4.5.2) then interchange the shortcut settings again. The final setting should be as follows:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/5741959c-45ec-4cac-82d1-a0dd47591a16)

You can see that Home (and Shift+Home) will do what you want then?

**Comment by cohensm52** [comment] 2023-06-22 21:13
Nope, that takes it back to what I originally complained about in #3171, where from here: 
![image](https://github.com/texstudio-org/texstudio/assets/79482316/4c153fc3-722f-4ada-acf6-e0b0d7536e5b)
Home takes the cursor to here: 
![image](https://github.com/texstudio-org/texstudio/assets/79482316/13f5ccc8-efb0-4c67-b7bd-3be8ac20aa19)
whereas I'd like it to go to here:
![image](https://github.com/texstudio-org/texstudio/assets/79482316/55087537-1c17-414c-ba9d-2606612c7a0f)

**Comment by octaeder** [comment] 2023-06-22 21:17
for me it does what you want. what settings do you have here:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/8813d4f2-6bef-4ad9-8afc-dc69c3d3b0db)

**Comment by cohensm52** [comment] 2023-06-22 21:31
I have it at soft line wrap at window edge. I tried the other options, but in all cases, if the cursor is on the first line of the paragraph, Home takes it to the left of the initial tabs, instead of to the right of those tabs.

**Comment by octaeder** [comment] 2023-06-22 21:44
I just felt the same problem so I had to fiddle around with restarting txs and reseting ini file. Problem seems to appear when using Home key in the first editor line (line number 1). So try it in some other editor line, please, to see if it works then.

**Comment by cohensm52** [comment] 2023-06-22 21:52
Maybe I've been confusing everything here. 
With your suggested settings, Home takes the cursor to the start of the paragraph no matter where the cursor started out, as shown here: 
![image](https://github.com/texstudio-org/texstudio/assets/79482316/13f5ccc8-efb0-4c67-b7bd-3be8ac20aa19)
If it starts out on a line NOT the first one in the paragraph, I'd like it to go to the start of that line, such as shown here for when it started on the second line of the paragraph: 
![image](https://github.com/texstudio-org/texstudio/assets/79482316/55087537-1c17-414c-ba9d-2606612c7a0f)
When I swap the settings back to what I think is the default (opposite to your suggested settings), then if the cursor is NOT on the first line of the paragraph, Home takes it to the start of the current line, as I'd like it to do, but if the cursor is on the first line of the paragraph, Home takes it to the left of the tabs, as shown here:
![image](https://github.com/texstudio-org/texstudio/assets/79482316/4ba5cba7-d3f9-43b2-96a7-0aaf42d0583a)

**Comment by octaeder** [comment] 2023-06-22 21:54
as I said, don't test in the line with number 1, insert an empty line above your text

**Comment by octaeder** [comment] 2023-06-22 21:55
and to be clear line 1 consists of three folded lines (say sub lines) due to line breaks.

**Comment by octaeder** [comment] 2023-06-22 22:07
@sunderme Please  check if smart home works for you in the first editor line. It seems that in this case the cursor finally reaches position 0 but after that doesn't jump back to start of text. Second editor line and so on seem not affected.

**Comment by cohensm52** [comment] 2023-06-22 22:08
I understand that the paragraph is really just one line, folded. I'd still like it to do what I'm describing, rather than going to the start of the paragraph, but maybe it just isn't possible.

**Comment by octaeder** [comment] 2023-06-22 22:12
did you try what I said? What we see is very likely a bug. So insert a new line at top of the editor, move the cursor to the second editor line and test behavior there. I'm pretty sure that the cursor will jump to start of text after cursor has reached a position within the first part (when you have line breaks) of text. After that it will jump between start of line and start of text. Try it!

**Comment by cohensm52** [comment] 2023-06-22 22:22
Yes, I did try what you said, or at least what I think you were suggesting. It didn't change anything, but then, maybe I misunderstood. The following is with your suggested settings:
![image](https://github.com/texstudio-org/texstudio/assets/79482316/e74b3eff-4ac3-46bf-a612-71f2e7be73ca)
Home takes the cursor to the position shown above, even if the cursor started in the second line of the second paragraph, such as shown here: 
![image](https://github.com/texstudio-org/texstudio/assets/79482316/e4e8dac9-3a58-4932-813b-5667dad93cbb)

**Comment by octaeder** [comment] 2023-06-22 22:37
So the cursor (now after inserting an empty line above the text) jumps at some time to start of text of editor line 2. That is one part of what you expect. The second part is that the cursor should touch start of text of that sub line where the cursor was (call it current sub line) before pressing home. This doesn't happen for you. But I can't reproduce this behavior. For me the cursor jumps in any case to start of text of the current sub line, and if it is not the first sub line then to start of the first sub line. From then on between this position and start of editor line. Editor line 1 seems to be an exception where the cursor will not move again after reaching start of editor line. But @sunderme will check this for sure.

**Comment by cohensm52** [comment] 2023-06-22 22:46
"For me the cursor jumps in any case to start of text of the current sub line, and if it is not the first sub line then to start of the first sub line." The two phrases within this sentence appear to me to be contradictory, so apparently, I'm misunderstanding something.
 
I also don't know what you're saying here: "From then on between this position and start of editor line."

Also, this does not just happen at Editor line 1. I'm writing a paper with many pages, and what I've described happens no matter where the cursor is in the paper, not just the very first line.

**Comment by octaeder** [comment] 2023-06-23 00:10
![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/d7ea6e03-cbea-4f80-9060-c2fd3236b274)

Each editor line (we may call it simply line) consists of sub lines (at least one) depending on line length and window width. The first sub line has a line number, while subsequent sub lines show a line wrap sign. Each editor line has a _line start_ (position left to the very first character -- here the tab arrow -- of that line) and a _first character in line_, that is also the first character of the first sub line. For all other sub lines line start and first character of line are the same (there is nothing like tab or space characters to the left).

When you set the cursor in a line then the cursor is in one of the line's sub lines. The line and sub line with the cursor are called the current line or current sub line, respectively. Assume the cursor is not in the first sub line. In this case pressing Home should always move the cursor to the first character of the current sub line, in case the cursor is to the right of that position.

When the cursor is in the first sub line then we have two options how the cursor will move when pressing Home. One option is called Smart Home that is default in 4.5.2. With this the cursor will move to the first character of the (editor) line when pressing Home, then to line start, then back to first character of line, and so on. Smart Home is enabled, when the Home key is assigned to operation _Move cursor to first character in line_ in the shortcut configuration. But if you assign Home key to operation _Move cursor to line start" then Smart home is disabled. This means that the cursor will jump to line start when it is in the first line while you press Home. And after that the cursor doesn't take any further action when pressing Home.

**Comment by cohensm52** [comment] 2023-06-23 02:22
Got it, thanks for the detailed explanation. You're too kind.
My Smart Home functions exactly as you've described it. I just prefer to have the Home key take the cursor to the first character in the current sub line, even if the current one is the first sub line.
I've now noticed that Shift+Home (without Smart Home) selects all the way to the start of the current sub line, whereas I think it used to select only to the first character in that sub line before I updated to 4.5.2. Although, this probably isn't important, since copying and pasting that selection seems to work the same way I'd want it to, anyway.

**Comment by sunderme** [comment] 2023-06-23 06:58
In the next version of txs, smart home will also stop at the start of a "subline", there should be no need to use the old startofline function.

**Comment by Niklas123Niklas** [comment] 2023-06-23 08:24
I came here because I was looking for the same issue that the cursor moves to the start of the line instead of the start of the subline when home is pressed once.
Just as an addition to that, the "end" button works as asked for the "home" button. In a subline, pressed once, the cursor moves to the last position of that subline, no matter if its the bottom most subline or not. Pressing the end button again, moves the cursor to the end of the line, no matter how many sublines are in between the current subline and the end of the line.
Could this behavior be added to the home button function? First press, go to the start of the current subline, at that position, a second press moves it to the first character of the line, and ideally, a third press then moves the cursor to the very start of the line?
Cheers, Niklas

**Comment by sunderme** [comment] 2023-06-23 22:24
Like with the end key:
Start of sub line, start of text,start of line

**Comment by octaeder** [comment] 2023-06-23 23:52
@sunderme You should check the following since the first line of editor seems to be an exception: Home key has no effect when the cursor is at line start and first character is to the right:
```
   abc
^
```

**Comment by sunderme** [comment] 2023-06-24 11:26
works fine here
I close this thread as it is confusing and from what I gather, resolved on the development branch.

**Closed by sunderme** 2023-06-24 11:26 UTC

**Comment by octaeder** [comment] 2023-10-07 12:33
Please, can someone retest smart home with win10 and the following case?

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/b54a3b4b-889c-4c8a-ab68-0bfc6d80b310)

Smart home should move the cursor mark from start of line to the right (as it is with any other line). But for me the cursor stays where it is in this case (current dev build, ...)

**Comment by cohensm52** [comment] 2023-10-07 17:24
I'm somewhat of a novice so am not sure I did exactly what you are asking for, but here's what I did and what I see. I have this, which is four lines in my configuration, all lines are indented by the same amount (so not aligned all the way to the left)---

\documentclass{article}
\begin{document}
      When I write to test this. But I need a paragraph with more lines than just one, so
      I'll continue typing, typing, typing, typing,typing, typing,typing, typing,typing, typing
      ,typing, typing,typing, typing,typing, typing,typing, typing,typing, typing,typing, typing,
\end{document}

If I put the cursor in the second line and hit home three times, first home takes it to the beginning of the second line, just to the left of the "I" in I'll; second time I hit home, cursor goes to the beginning of the first line, just to the left of the "W" in When; and third time I hit home, the cursor moves completely to the left, that is, to left of the indent. Seems like that's what we want, no?
________________________________

**Comment by octaeder** [comment] 2023-10-07 17:31
What you describe is exactly the behavior expected in any line. What I want to know is what happens when you indent the first line (\documentclass) and try home there. I ask what happens when the cursor is at the beginning of the line (left to indent) and you press home?

**Comment by cohensm52** [comment] 2023-10-07 17:48
When I indent the first line like this
      \documentclass{article}
and then put cursor all the way to left of that indent, hitting home does not move the cursor at all. Which is different than if I do the same thing on any of the other lines.
And I'm using Windows 10, TexStudio 4.6.3
________________________________

**Comment by octaeder** [comment] 2023-10-07 18:51
Thanks, that shows that we both see that issue.
@sunderme did you see that line 1 is the one affected?
