### ISSUE TITLE
Horizontal lines appear when using magnifying glass tool in pdfviewer

### ISSUE THREAD

**Issue by MichaelPPieper** [texstudio-org/texstudio#1808] opened 2021-10-05 21:40 UTC
Whenever I use the magnifying glass, these annoying horizontal lines appear in the pdf viewer. They remain after I stop using the magnifying tool, and stay until I scroll down the pdf or otherwise force it to reload. This never happened on previous versions of texstudio for me; I just updated to 4.0.0 today. I tried uninstalling/reinstalling, closing/reopening, and tested multiple files. I'm running Windows 10 Home edition, in case that's relevant. Hopefully the attached image clarifies what I am referring to.

![image](https://user-images.githubusercontent.com/86335289/136106238-ee11ecaf-f540-44fe-bbc5-3176a5e66e43.png)

**Comment by Alexander-Wilms** [comment] 2021-10-05 21:42
Duplicate of #1773

**Closed as completed** 2021-10-10 11:53 UTC
Labels: duplicate
