### ISSUE TITLE
Adding Full Path to Latex Tools

### ISSUE THREAD

**Issue by pirlite2** [texstudio-org/texstudio#2581] opened 2022-09-14 16:05 UTC
Following on from the now closed and resolved issue where upgrading TXS appeared to install the default (out-of-date) repo version of TexLive and messed up building a tex file that had worked properly before the upgrade:

Thinking on this, this would seem to be a case of TXS being 'broken' by an external event and failing to detect the problem. Therefore, it seem to be a classic case of TXS failing _silently_, which is something that software engineering says should never happen!

Could I suggest a minor change the TXS configuration to specify the full path to the intended Latex tools in much the same way as programming IDEs specify the path to the toolchain. So the addition of another QLineEdit box in the configuration dialog allowing the user to specify the path to the intended TexLive installation, whether this be the default repo version in /usr/bin (on Linux), or /usr/local/textlive/2020/bin, or whatever. This would also require TXS to invoke the all external tools by prepending the texlive path.

That, I think, would be bullet proof and would cure the failing silently issue!

Peter

**Comment by sunderme** [comment] 2022-09-14 16:21
no.
Some tools even call sub-commands themselves and rely on PATH.
In general path works just fine.
The issue is rather that .bashrc and desktop do not necessarily use the same path, the later probably using .profile.
It is not txs objective to work-around linux desktop environment shortcomings.

That does not hinder you to follow your strategy nonetheless.

**Comment by pirlite2** [comment] 2022-09-14 16:47
> "Some tools even call sub-commands themselves and rely on PATH."

Really? I am curious. Which ones? (This has implications for another project I am thinking about.)

I agree that the existence of simultaneous path sets (one for the shell, one for the GUI) under Unix is a nuisance. This, of course, is an historical accident. But we are where we are. 

What is your response to the 'failing silently' issue?

**Comment by sunderme** [comment] 2022-09-14 16:53
can't remember but I had the problem. So, probably one of the helper tools (index,bibtex,etc.)

the scenario you want to fix is texlive installed outside of the package manager and the package manager also installed texlive, so a bit special.

The argument for PATH based is that is works on usual systems out of the box, the path is simple to see errors and update is simple as PATH just points to the new bin. (and texlive regular changes base name)

**Comment by pirlite2** [comment] 2022-09-14 18:25
> "can't remember but I had the problem. So, probably one of the helper tools (index,bibtex,etc.)"

Hmmm... I shall dig into that. 

> "the scenario you want to fix is texlive installed outside of the package manager and the package manager also installed texlive, so a bit special."

Except I have now fallen over this problem twice! The argument against the default repo versions of textlive is that they are usually very out of date. So there is a good reason to use a separately installed texlive. The fact that the Ubuntu package manager seems to interpret "recommended" as must install regardless and without asking is another, completely different problem. 

P.

**Comment by sunderme** [comment] 2022-09-14 18:35
again, if you want to set all commands to full path, you can do so.
No need for everyone else to follow along.

**Comment by pirlite2** [comment] 2022-09-14 19:06
...except if you are right that some programs spawn other programs, then specifying the full path in the TXS configuration will not save me!  If the package manager silently installs the repo version texlive in /usr/bin again, the process spawn will switch from my local texlive to the older version of texlive in /usr/bin midstream! That sounds s recipe for complete disaster!

P.

**Comment by sunderme** [comment] 2022-09-16 12:16
closing, as I will not implement this.
The user is free to set it up, so no blocking behaviour by txs either.

**Closed by sunderme** 2022-09-16 12:16 UTC
