### ISSUE TITLE
Git command integrate 

### ISSUE THREAD

**Issue by juliandragon** [texstudio-org/texstudio#340] opened 2018-09-30 01:01 UTC
### Environment
- TeXstudio: <2.12.6>
- Qt: <integrate Git command>
- OS:  Windows 10
- TeX distribution: < texlive>

### Expected behavior
Support git command directly, not only with SVN

**Comment by rommeswi** [comment] 2018-10-19 07:51
https://tex.stackexchange.com/a/368027/87274 gives some hints how to generate similar behavior using the current versions. That perhaps also shows that it would not be too difficult to make this a feature.

**Comment by thatlittleboy** [comment] 2018-11-15 18:41
Dupe of #59 ?

**Comment by chrisma** [comment] 2018-11-15 22:48
For the sake of documentation: The closed (duplicate) issue #59 already had 13 :+1: and 5 :heart: 

![image](https://user-images.githubusercontent.com/1652117/48586644-c9508700-e930-11e8-8190-f399a560b7ce.png)

**Comment by mlainz** [comment] 2020-06-03 12:04
Overleaf has git integration, and many of my collaborators dislike its web-based editor.
It would be very interesting to have an easy to use git integration in texstudio.
This would allow us to have a good editor and the social features of Overleaf.

**Comment by yashpalgoyal1304** [comment] 2022-11-13 06:30
> having support for version control systems within an editor can be handy as integration makes some workflows simpler. This is most likely why many other IDEs have this feature

i understand this, but i agree more with @ Piraty - the fact that EVERY editor has to implement this on their own, really means that there's no good standalone diff/VCS GUI client out there which is flexible enough to be used with other editors - and in which case, effort should be concentrated by all communities to create such one.... rather than, yeah, like per said, duplication of it in editors

**Comment by sunderme** [comment] 2022-11-13 18:21
txs has some basic git integration but nothing fancy, see manual or file/git

**Closed by sunderme** 2022-11-13 18:21 UTC
Labels: enhancement
