### ISSUE TITLE
Newabbreviation label does not appear

### ISSUE THREAD

**Issue by judober** [texstudio-org/texstudio#1323] opened 2020-10-29 09:20 UTC
### Expected behavior
When using `\newabbreviation` of the `glossaries-extra` package to define an abbreveation and then citing with `\gls{}`, the labels should appear in Texstudio.

### Actual behavior
The labels do not appear.

### Fix
I allready opend a pullrequest which adds a `glossaries-extra.cwl` that fixes the problem. #1321

**Comment by muzimuzhi** [comment] 2020-10-29 10:53
If current issue is an exact duplicate of #1322, then this one can be closed.

**Comment by judober** [comment] 2020-10-29 13:44
Yes, sorry for the double post

**Comment by muzimuzhi** [comment] 2020-10-29 17:26
(_whisper:_ As the one who opened this issue, you can close it by yourself.)

**Closed** 2020-10-29 19:52 UTC
