### ISSUE TITLE
TexStudio not responding for a while

### ISSUE THREAD

**Issue by xR2** [texstudio-org/texstudio#487] opened 2019-01-22 18:07 UTC
### Environment

- TeXstudio 2.12.14 (git 2.12.14)
- Using Qt Version 5.8.0, compiled with Qt 5.8.0 R
- OS: Windows 10 Pro, Version 1809
- TeX distribution: texlive
### Expected behavior
Just run, without not responding.

### Actual behavior
I am having this issue only **after** the **last update**.
It freezes randomly. Most of the time I am just building simple documents. The screen becomes white and title displays  **No Responding** for a while. After almost one second, its working again and does build without any issue.
This issue also happen when I tried loading and saving some files, but mostly randomly.

### How to reproduce
I just open a random file and try to built.
Its not always but seems to affect more files saved to HDD then the ones on SSD. In _taskmanager_ I don't see any Disk usage before, during or after the freeze so maybe there is nothing to do with.

**Comment by jonasstein** [comment] 2019-01-22 18:50
Have you tried to start with a new config/in a different user profile? You can see, if the error is caused by TeXstudio and its library, or the config.

**Comment by xR2** [comment] 2019-01-29 09:01
Actually the icons overlay didn't solve my issue. What does solve is disabling SVN in TexStudio, which is not a good solution.

**Comment by sunderme** [comment] 2019-02-02 11:04
this rather like a problem with Our svn.
txs makes use of svn only when saving , but then it blcoks the gui

**Comment by sunderme** [comment] 2019-03-10 09:50
won't fix

**Closed by sunderme** 2019-03-10 09:50 UTC
