### ISSUE TITLE
Macros with greek letter trigger not saving correctly.

### ISSUE THREAD

**Issue by MolochBaal** [texstudio-org/texstudio#498] opened 2019-02-06 20:28 UTC
### Environment
- TeXstudio: 2.12.14
- Qt: 5.8.0
- OS: Windows 10
- TeX distribution: MikTeX

### Expected behavior
Making a macro whose trigger is a greek unicode letter (e.g. "α") should be possible.

### Actual behavior
When a macro is created whose trigger is a greek unicode letter, it is replaced with another character.

### How to reproduce
1. Create a new macro, with its trigger being, for example, a greek unicode letter "α".
2. Close and reopen Texstudio.
3. Inspect the previously created macro: it no longer has "α" as a trigger, but "a".

**Comment by sunderme** [comment] 2019-02-06 20:45
works fine on linux
I'll recheck on win later

**Comment by sunderme** [comment] 2019-03-01 21:16
I can reproduce the behaviour on win.

**Comment by sunderme** [comment] 2019-03-01 21:21
this seems to be already fixed in the repository. You could try a development build, see webpage.

**Closed by sunderme** 2019-03-01 21:21 UTC
