### ISSUE TITLE
GIT instead of SVN

### ISSUE THREAD

**Issue by OgreTransporter** [texstudio-org/texstudio#911] opened 2020-01-30 12:39 UTC
SVN is integrated in TeXstudio. I think it makes sense to replace SVN with GIT in the future.

**Comment by MeanSquaredError** [comment] 2020-01-30 12:48
I still use SVN for my local projects because it works well and there is no point in replacing something that works.

So if anyone needs GIT it is fine to add support for it, but SVN should stay too.

**Comment by OgreTransporter** [comment] 2020-01-30 13:55
I use GIT for my local projects because it works well and there is no point in replacing something that works.

For editing papers or books in a team, Git has proven to be more useful because there are automatically many backups of the work. The decentralized approach has become particularly popular for students' theses. SVN server broken means work gone, if one Git clone is gone, it doesn't matter - as long as you have another one.

**Comment by sunderme** [comment] 2020-01-30 19:06
for none programmers, I also think that svn is easier to handle.
If someone wants to provide code to *additionally* handle git, be my guest.

**Comment by MeanSquaredError** [comment] 2020-01-30 22:05
I did not argue about the merits of SVN vs GIT. My point was (probably not well articulated) that SVN is still being widely used and getting rid of SVN support is a sure-fire way to cause problems to users (and therefore get user complaints). Of course adding GIT support sounds like a good idea (as long as someone provides the pull request with the code).

**Comment by timhoffm** [comment] 2020-02-01 12:47
An embedded terminal (c.f. #864) would reduce the need for explicit VCS support. All actions could be performeded.

**Comment by MeanSquaredError** [comment] 2020-02-01 18:24
I think as a temporary workaround it is possible to create some macro that would do the commit through a `system()` call and then to assign a shortcut to that macro.

**Comment by timhoffm** [comment] 2020-02-01 18:45
That is already documented:
https://github.com/texstudio-org/texstudio/wiki/Scripts#git-commit-and-push

**Comment by timhoffm** [comment] 2020-02-01 18:45
That is already documented:
https://github.com/texstudio-org/texstudio/wiki/Scripts#git-commit-and-push

**Comment by timhoffm** [comment] 2020-02-01 18:45
That is already documented:
https://github.com/texstudio-org/texstudio/wiki/Scripts#git-commit-and-push

**Comment by OgreTransporter** [comment] 2020-02-03 12:02
Or you outsource the SCM commands in Qt plugins?
https://doc.qt.io/qt-5/plugins-howto.html

**Comment by sunderme** [comment] 2020-02-03 14:01
I would rather keep it simple...

**Comment by OgreTransporter** [comment] 2020-02-07 08:00
- #340
- #59

**Comment by SillieWous** [comment] 2020-02-18 21:26
I am not familiar with the development process of TexStudio and use of external libraries. But may be libgit2 is a good option to integrate git. It supports all platforms, well documented and it is still an active project.

**Comment by sunderme** [comment] 2020-02-19 17:10
using the command line git program is sufficient.
no need for further dependencies.

**Comment by MikeGitb** [comment] 2020-04-06 14:22
Except for managin a diff and/or merge, I personally don't think integrating git into the Editor UI has andy advantages over using the git command line program. But maybe that is just me, who is pretty used to use git from the command line all the time -- especially whan programming.

**Comment by jonasstein** [comment] 2020-04-18 20:51
duplicate of #340?

**Closed** 2021-10-16 11:44 UTC
Labels: enhancement, help wanted
