### ISSUE TITLE
Root Document does not detect automatic again

### ISSUE THREAD

**Issue by zionmann** [texstudio-org/texstudio#3411] opened 2023-12-08 07:38 UTC
### Environment
- TeXstudio: 4.7.1
- Qt: 
- OS: Windows11
- TeX distribution: 

### Expected behavior
As of previous installation, root document detects automaticly and detects correctly, 

### Actual behavior

as the newly installed version 4.7.1 not do automatic detection, only compiles the currently displayed tex file, so that much more error without root document

**Comment by sunderme** [comment] 2023-12-08 08:46
We need a concrete example files.

**Comment by NTrnka** [comment] 2023-12-12 10:29
I have the same issue, for 4.7.0 and 4.7.1 and while reducing my documents to a minimal working example I found out the Problem on my side: It seems to be a Problem when there is a comment at the end of the text in between  \begin{document} and \end{document}.

# Environment
    TeXstudio: 4.7.1
    Qt: 6.6.1, kompiliert mit Qt 6.6.1 R
    OS: Windows10
    TeX distribution: TexLive 2022

# Expected behavior
A root document loads a subdocument via \include{}. Opening the subdocument and clicking on Compile finds the root document and compiles correctly. 

# Actual behavior
4.7.0 and 4.7.1 do not detect the root document, but try to compile currently displayed tex file, which fails.

# How to reproduce
Find a minimal working example in
[BugReport.zip](https://github.com/texstudio-org/texstudio/files/13646821/BugReport.zip)
Open Root.tex and subdocument.tex. Root.tex compiles correct, subdocument.tex does not find Root.tex but tries to compile alone and fails.

Editing any character of the comment in Root.tex in any way solves the problem as long as Texstudio is opened, so compiling subdocument.tex finds Root.tex and compiles correctly, even if the changes are undone. Closing and reopening Texstudio resets the error, so subdocument.tex fails again.

**Comment by sunderme** [comment] 2023-12-12 17:34
not reproducible. (linux)
any non-default settings ?

**Comment by acuiko** [comment] 2023-12-12 18:12
I confirm the situation presented by [zionmann](https://github.com/zionmann) and [NTrnka](https://github.com/NTrnka). Only want to add that in my case there is magic comment in the main file like `% !TEX root = root.tex` and chapter files are located in subfolder if that matters.
-root.tex (`% !TEX root = root.tex` ... `%Some random comment` ... `\input{chapters/chapt1.1}` .... )
|---chapters\chapt1.tex
|---chapters\chapt2.tex

TeXstudio: 4.7.1 (git 4.7.1)
Qt: 6.6.1, compiled with Qt 6.6.1 R
OS: Windows11
TeX distribution: TexLive 2022

**Comment by NTrnka** [comment] 2023-12-12 18:36
In my case there is no difference, if the chapter files are in subfolder or the same folder as the root document.

I think I dont have non-default settings except dark mode (Style: Adwaita Dark (txs) and Scheme:  Modern - dunkel)

**Comment by sunderme** [comment] 2023-12-12 18:37
screencast ?

**Comment by sunderme** [comment] 2023-12-12 18:44
and please upload texstudio.ini here

**Comment by NTrnka** [comment] 2023-12-12 18:45
Screenshots of my Configuration:
[Config.zip](https://github.com/texstudio-org/texstudio/files/13652083/Config.zip)

**Comment by NTrnka** [comment] 2023-12-12 18:47
sunderme: Sorry, where do I find the texstudio.ini?

**Comment by acuiko** [comment] 2023-12-12 18:56
[NTrnka](https://github.com/NTrnka) 

> sunderme: Sorry, where do I find the texstudio.ini?

%appdata%/texstudio/texstudio.ini

**Comment by sunderme** [comment] 2023-12-12 19:07
okay, found it.
![grafik](https://github.com/texstudio-org/texstudio/assets/14033169/db7261cf-2832-4c18-807d-8142b0aa2b8c)
with that, I have found and fixed the issue.

**Comment by sunderme** [comment] 2023-12-12 19:08
any particular reason, why that option is not set ?

**Comment by NTrnka** [comment] 2023-12-12 19:14
actually no, its not on purpose. I did not change options for quite some time, so either it has always been like that, or it was so long ago that I can't remember changing it.

**Closed** 2023-12-12 19:23 UTC

**Comment by acuiko** [comment] 2023-12-12 20:15
> any particular reason, why that option is not set ?

[sunderme](https://github.com/sunderme), are you suggesting that it is normal that without the appropriate option selected, the detection of the root document became possible in the latest version of the program only by manipulations with comments? Previously it worked without this option set and without "fiddling" with comments in the root document.

**Comment by sunderme** [comment] 2023-12-12 20:41
There was a bug when autoloading is disabled, which is fixed in the source code now.

Not activating autoloading reduces txs capabilities quite significantly, so i am curious about the why.
