### ISSUE TITLE
Accept selection of text in \textsf

### ISSUE THREAD

**Issue by LieuweVinkhuijzen** [texstudio-org/texstudio#1612] opened 2021-05-01 10:46 UTC
Use case: I have written a line of text in the editor, and I wish to highlight a word using \textsf{important} (or using \textbf{important}, or some other font)
    "This is a line with an important word."
Suppose I wish to highlight the word "important". I will select the text, and start typing \textsf. This will delete the word "important", so that the text is now
   ```This is a line with an \textsf<cursor> word.```
Once I open a curly bracket, the editor inserts the word "important" within curly brackets. Here TexStudio is helping the writer, by offering the suggestion of putting the word "important" inside of "\textsf{important}". Looking promising!
    "This is a line with an \textsf{important} word." (the text "important" is selected)
However, if I now press ```<Enter>```, intending to accept the editor's helpful suggestion, the word "important" disappears, and is replaced by a line-break. That is not what I intended.
    "This is a line with an \textsf{
    word."
In order to accept the suggestion, I have to press the following keys: ```<right arrow> <left arrow> <}>```. This is not a convenient key sequence, and also not intuitive.

I propose: Pressing the ```<Enter>``` key should allow me to "accept" TexStudio's suggestion of \textsf{important}

### Who will benefit with this feature?
I will benefit. Perhaps there are other places where TexStudio's editor's suggestions can be more conveniently accepted.

Thanks in advance.

**Comment by sunderme** [comment] 2021-05-01 14:37
not sure what the problem is.
The completer gives suggestions, normally you accept by pressing "enter". The completer has a mode to assume non-word characters as acceptance as well.(can be turned on/off)
When using the cut-buffer, the inserted text is highlighted first. This serves to have an easy way to accept or discard the inclusion of the cut-buffer (previously selected text)
It is a bit unclear what you type and why. Also what "pressing the key" is.

Please, less prose, more precise steps.

**Comment by JonathanLevine657** [comment] 2021-05-02 00:07
@LieuweVinkhuijzen, instead of <kbd>}</kbd> , you can use the right arrow key, which "accepts" and moves the cursor past the inserted text.

Changing the behavior of `<kbd>Enter</kbd>` is not realistic. This behavior is also consistent with other popular editors. Use the arrow key and you'll quickly get used to it.

As a side note, seems like you're new to Github. You should know that enclosing text in  `<` and `>` doesn't have the intended effect. Instead, github thinks you're using HTML and (usually) just hides the word.  Have a look at the [GitHub Flavored Markdown](https://github.github.com/gfm/) guide, and make a habit of using the `preview` tab.

In particular, If you want to indicate a keyboard combination, you can use the markup 
`<kbd>MyKey</kbd>` to get <kbd>MyKey</kbd>.

**Comment by sunderme** [comment] 2021-05-02 06:51
I have edited the original post to make readable (placed all <...> in verbatim tags)

**Comment by sunderme** [comment] 2021-05-02 07:01
seeing now the complete post, I am a bit confused.
Typing ```\textsf``` should trigger the completer and show the command ```\textsf{text}```, which needs to be selected from the drop-down via <kbd>Enter</kbd>.
The way it is described, the completer does not show-up automatically. What options are changed here ?
After starting the completer with the typing of <kbd>{</kbd>,the cut-buffer text is selected and the cursor is just in front of the closing brace. Moving the cursor via keys (e.g. <kdb>right arrow</kbd>) is all you need to do. The closing is shown as place-holder (box around it), but that can be ignored.

**Comment by sunderme** [comment] 2021-05-07 21:25
no feedback

**Closed by sunderme** 2021-05-07 21:25 UTC
