### ISSUE TITLE
With Adwiata (txs) style the tooltip size is too big in TXS3.0.3

### ISSUE THREAD

**Issue by hair-splitter** [texstudio-org/texstudio#1412] opened 2020-12-31 14:18 UTC
### Environment
- TeXstudio: TeXstudio 3.0.3 (git 3.0.3)
- Qt: Qt 5.12.3 R
- OS: Windows 10 (64bit)
- TeX distribution: TeX Live 2020

Options / Configure TeXstudio / General
Style: Adwiata (txs)

Then the tooltip size is too big.

**Comment by hannes101** [comment] 2021-01-02 17:42
This seems to be a duplicate of https://github.com/texstudio-org/texstudio/issues/1370

**Comment by sunderme** [comment] 2021-01-03 16:28
seems to be a windows only issue.

**Comment by Stimmenhotel** [comment] 2021-01-05 12:51
Definitely a Adwaita (txs) issue, disappears after switching back to windows, fusion or vista.

**Comment by JanWaldhorn** [comment] 2021-01-11 17:29
> 
> 
> Definitely a Adwaita (txs) issue, disappears after switching back to windows, fusion or vista. Can't test on any linux disto myself. But I believe it was already tested.

I tried it today in a VM with Ubunut 20.4, but get no adwaita displayed at all. Strange...

![grafik](https://user-images.githubusercontent.com/57268762/104216819-db5be080-543a-11eb-8754-0c233fa75d88.png)

**Closed** 2021-02-07 08:25 UTC
