### ISSUE TITLE
Grid stripe occurrence around the mouse cursor when PDF reviewing.

### ISSUE THREAD

**Issue by Tridu33** [texstudio-org/texstudio#2025] opened 2021-12-18 04:24 UTC
### Environment
- TeXstudio: TeXstudio 4.1.1 (git 4.1.1) built by Qt 6.2.1 R .
- OS: Windows 11
- TeX distribution: texlive

### Expected behavior

The silky-smooth reading experience.

### Actual behavior

Grid stripe occurrence around the mouse when PDF reviewing.
![](https://pic1.zhimg.com/v2-ed1e8e58c96f073a5ce33d02f2c2afec_b.jpg)

### How to reproduce
Update to windows11 from windows 10, anyother PDF reader will never had Grid stripe occurred.

**Comment by muzimuzhi** [comment] 2021-12-18 06:37
duplicate of #1773

**Closed** 2021-12-18 07:20 UTC
