### ISSUE TITLE
Opening and then closing the side panel moves the view to the end of the LaTeX document

### ISSUE THREAD

**Issue by ColourGrey** [texstudio-org/texstudio#3530] opened 2024-02-22 11:24 UTC
### Environment
- TeXstudio: 4.7.2
- Qt: 6.6.1
- OS: Windows 10 64bit
- TeX distribution: MikTeX

### How to reproduce
Begin with the side panel hidden. In the lower left corner, press the "Side Panel" button once, to display the side panel. Press it once more, to hide the side panel.

### Actual behavior
The view in the LaTeX source pane moves to the end of the document, for no reason. This should not happen.

### Expected behavior
The view in the LaTeX source pane should not change after showing and then hiding the side panel.

### Further comments
The cursor does not follow the change of view, it stays where it should, i.e. at the current position. Similarly, the view in the PDF pane does not change either. Only the view in the source file pane changes.

**Comment by ColourGrey** [comment] 2024-02-22 17:58
I am attaching my "texstudio.ini" file, renamed to "texstudio.ini.txt" in order to please the Github uploader. I have modified it only to purge my private data from it (recent files, search history etc.)
[texstudio.ini.txt](https://github.com/texstudio-org/texstudio/files/14377580/texstudio.ini.txt)

Indeed, the LaTeX file should be larger than can fit a single screen; in my case, it has some 1350 numbered lines. The current line should be anywhere but not close to the end of the document, or else you will not see anything of what I see; the idea is not to be on the last visible screen when trying to reproduce the bug.

Screenshots would not help, because they would not be able to catch the instantaneous jump from the current view to the end of the document.

**Comment by octaeder** [comment] 2024-02-23 08:21
I can't reproduce. I also had to disable option (`Files\CacheStructure=false`)
![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/73b39f24-1b2b-46ee-98cc-a816bf26efcd)
(s. last line) in your ini file. Maybe try renaming your texstudio profile folder (s. `%appdata%`) and test again.

**Comment by ColourGrey** [comment] 2024-02-23 16:06
The bug is subtler than I had described, and a more complex sequence of actions has to be performed in order to trigger it. I shall return with more detailed instructions.

**Comment by sunderme** [comment] 2024-03-03 08:42
I will close this then.
Please open (or reopen) this when we have a reproducible test case.

**Closed by sunderme** 2024-03-03 08:42 UTC
