### ISSUE TITLE
Very big descriptive boxes

### ISSUE THREAD

**Issue by Miguelpage** [texstudio-org/texstudio#1462] opened 2021-01-31 04:53 UTC
the descriptive signs of the functions do not work well and look gigantic, just like in the photo,

![image](https://user-images.githubusercontent.com/9299588/106374879-ce5d4d80-6365-11eb-8a6c-052fea16893e.png)

### Environment
- TeXstudio: 3.0.4
- Qt:  5.12.3, compiled with Qt 5.12.3 R
- OS: Windows 10 1809 LTSC
- TeX distribution: last texlive
- TeXstudio installed from: binary

### Expected behavior
that fits the font or those boxes can be turned off 

### Actual behavior

very big boxes
### How to reproduce
leaving the cursor over an icon for a few seconds or when configuring

**Comment by sunderme** [comment] 2021-01-31 08:37
this is the adwaita style.
Please try the latest dev build. It is probably fixed. https://bintray.com/sunderme/texstudio/texstudio-win#files

**Comment by muzimuzhi** [comment] 2021-01-31 16:40
duplicate of #1370

**Closed** 2021-02-06 18:13 UTC
