### ISSUE TITLE
TeXstudio crashes after opening a document using the MinionPro package

### ISSUE THREAD

**Issue by SFr682k** [texstudio-org/texstudio#3596] opened 2024-04-10 20:24 UTC
### Environment
- TeXstudio: 4.7.3
- Qt: 5.15.12
- OS: Fedora 39
- TeX distribution: TeXLive 2024 (vanilla)
- Additional package: [MinionPro](https://github.com/sebschub/FontPro) installed in TEXMFLOCAL

### Expected behavior
After opening the document, TeXstudio runs without excessive resource usage and does not crash.

### Actual behavior
1. After opening the document (see MWE below), a process `/usr/local/bin/pdflatex -draftmode -interaction=nonstopmode --disable-installer /tmp/aDvqbV.tex` appears, which runs for about 30s, has 100% CPU usage and produces a *HUGE* (1.7 GB) logfile `/tmp/aDvqbV.log`
2. Afterwards, TeXstudio itself has 100% CPU and up to 3.4 GB RAM usage – probably since it tries to open the log
3. TeXstudio crashes

### How to reproduce
Open the following MWE in TeXstudio:
```latex
\documentclass{minimal}
\usepackage{MinionPro}
\begin{document}
    Hello World!
\end{document}
```

### Additional information
Backtrace:
```
c++ exception forced kill in 000055d3638e6840 (TXS-Version 0.0.0++ R )
[bt] /usr/bin/texstudio(_Z15print_backtraceRK7QString+0x4) [0x55d35f174664]
[bt] /usr/bin/texstudio(_ZN9Texstudio16recoverFromCrashEv+0x101b) [0x55d35f082c3b]
[bt] /lib64/libstdc++.so.6(+0xb4f6c) [0x7f64934b4f6c]
[bt] /lib64/libQt5Core.so.5(+0xb2858) [0x7f64938b2858]
[bt] /lib64/libc.so.6(+0x8e897) [0x7f64932ac897]
```

Contents of `/tmp/aDvqbV.tex`:
```latex
\documentclass{article}
\usepackage{filehook}
\usepackage{currfile}
\AtBeginOfEveryFile{\message{^^Jentering file \currfilename ^^J}}
\AtEndOfEveryFile{\message{^^Jleaving file \currfilename ^^J}}
\tracingonline=1
\tracingassigns=1
\usepackage{MinionPro-FontDef}
\tracingassigns=0
\AtBeginOfEveryFile{}
\AtEndOfEveryFile{}
\begin{document}
\end{document}
```

The code above does not compile since `MinionPro-FontDef` is missing a control sequence `\Mn@scale`, which is defined by `MinionPro` while processing package options.  When running `pdflatex` in nonstopmode, this causes an endless loop and therefore a huge log.

**Comment by muzimuzhi** [comment] 2024-04-11 06:41
> 1. After opening the document (see MWE below), a process `/usr/local/bin/pdflatex -draftmode -interaction=nonstopmode --disable-installer /tmp/aDvqbV.tex` appears, which runs for about 30s, has 100% CPU usage and produces a _HUGE_ (1.7 GB) logfile `/tmp/aDvqbV.log`

> When running `pdflatex` in nonstopmode, this causes an endless loop and therefore a huge log.

These two behaviors both look like (La)TeX usage issues, especially if they reproduce when you compile the tex file from command line.

**Comment by sunderme** [comment] 2024-04-11 06:49
The issue is that txs runs generates and runs that tex file to extract the cwl for MinionPro.
Simplest solution is to provide a cwl in txs.

**Comment by sunderme** [comment] 2024-04-11 07:27
Okay, we already have MinionPro.cwl, but that references "MinionPro-fondef.cwl" which does not exist and txs tries to generate it with the problematic results.
I have removed that include from the cwl.
Please try the dev build https://github.com/texstudio-org/texstudio/actions/runs/8643050733 (or newer)

**Comment by sunderme** [comment] 2024-04-11 07:31
should be fixed, please state here if that assumption is incorrect.

**Closed by sunderme** 2024-04-11 07:31 UTC
