### ISSUE TITLE
Installer freezes when upgrading

### ISSUE THREAD

**Issue by mmgthb** [texstudio-org/texstudio#3546] opened 2024-03-02 14:51 UTC
### Environment
- TeXstudio: 4.7.2
- Qt: 6.6.2
- OS: Windows 11
- TeX distribution: texlive

### Expected behavior
When running the installer of a newer version, the installation ends successfully with the new version of texstudio

### Actual behavior
- The installer freezes at some point (e.g. see below). The specific point vaires, but mostly it happens while unpacking some png.
- It can be solved by completely uninstalling texstudio and then reinstall it. But I think that's not the sense of an upgrade from one minor version to another (e.g. 4.7.2 to 4.7.3). 

![image](https://github.com/texstudio-org/texstudio/assets/107367348/12559e70-ba32-48d6-ba2f-9277b30b58ff)

**Comment by sunderme** [comment] 2024-03-02 19:02
can't reproduce (win11)

**Comment by sunderme** [comment] 2024-03-06 10:03
not reproducible on second PC, closing.

**Closed by sunderme** 2024-03-06 10:03 UTC
