### ISSUE TITLE
Insert filename on the files sidebar inserts folder name instead

### ISSUE THREAD

**Issue by nathanaeljsmith2** [texstudio-org/texstudio#3808] opened 2024-09-24 20:30 UTC
### Environment
- TeXstudio: 4.8.1
- Qt: Qt Version 6.7.1, compiled with Qt 6.7.1 R
- OS: Windows 11
- TeX distribution: miktex

### Expected behavior
Right clicking on a file in the Files tab on the sidebar, and choosing Insert filename, should insert the filename into the document.

### Actual behavior
Right clicking on a file in the Files tab on the sidebar, and choosing Insert filename, inserts the folder name into the document.

**Comment by octaeder** [comment] 2024-09-24 21:13
same for me, win10, current build

**Comment by foreachthing** [comment] 2024-09-25 04:35
I agree with @nathanaeljsmith2. Same thing with my setup:

* Windows 10 Enterprise 22H2 19045.4651
* TeXstudio 4.8.3 (git 4.8.3)
* Qt Version 6.7.2, compiled with Qt 6.7.2 R

**Comment by octaeder** [comment] 2024-09-25 06:17
texstudio.cpp, l. 5355: add `File` to `absolutPath`:
`const QString fn=getRelativeFileName(fi.absoluteFilePath(),rootDir);`
This gives the file name including the relative directory path beginning from the tex file folder shown in the side pane: `abc/myfile.jpg`. I'm not sure, maybe `abc` should not be present.

**Comment by foreachthing** [comment] 2024-09-25 06:54
> I'm not sure, maybe `abc` should not be present.

I think it should. If I want to include a file, the subfolder needs to be there. Same for images.

**Comment by octaeder** [comment] 2024-09-25 08:09
it is a little bit complicated to explain: `abc/` is the folder of the tex file to compile, i.e. `abc/` is the folder whose files and folders are shown in the side pane. If there is a folder `abc/pics` then `pics/` should be in the path. I assume that tex won't find the files when adding `abc`.

**Comment by octaeder** [comment] 2024-09-25 13:47
The problem is in `utilsSystem.cpp` (l. 497ff):

```cpp
QString getRelativeBaseNameToPath(const QString &file, QString basepath, bool baseFile, bool keepSuffix)
{
	basepath.replace(QDir::separator(), "/");
	if (basepath.endsWith("/")) basepath = basepath.left(basepath.length() - 1);

	QFileInfo fi(file);
	QString filename = fi.fileName();
	QString path = fi.path();
	if (path.endsWith("/")) path = path.left(path.length() - 1);
	QStringList basedirs = basepath.split("/");
	if (baseFile && !basedirs.isEmpty()) basedirs.removeLast();
```

Var `basdir` is the second parameter with value `rootDir` set by caller. The value is ok, but last line shown here removes the last/lowest dir from the path (the dir containing the tex file). After that anything in commen is removed from basdirs and dirs. The difference remaining is the dir removed previously and will be added to the output.

I think you can't use `getRelativeBaseNameToPath` in this case.

**Comment by sunderme** [comment] 2024-09-25 18:33
fixed with 04bdbca9ba773dfd1786d4ef2eaf70f989c48a1b

**Closed by sunderme** 2024-09-25 18:33 UTC

**Comment by octaeder** [comment] 2024-09-25 19:04
@sunderme your solution inserts the filename (i.e. including suffix). Usually the suffix is missing. Folders are inserted without slash at the end so it is not clear from the text if this is a file or not.

**Comment by sunderme** [comment] 2024-09-25 19:29
I don't understand.
It is a user triggered action, supposedly to put filename/foldername easily into a latex function and that is what is achieved ?

**Comment by octaeder** [comment] 2024-09-25 19:38
The folder is a special case that my solution implemented, but not necessary (`pics/`).
Inserting files: until now used:
`\include{subdoc}` and `\includegraphics{image}`. For the latter you can define which extension should be used. Those who want to do so need to remove the suffix. But ok, maybe a corner case.
