### ISSUE TITLE
Autocomplete and highlighting of package names, Linux does not work.

### ISSUE THREAD

**Issue by fdiazruiz** [texstudio-org/texstudio#1975] opened 2021-11-29 04:06 UTC
### Environment

- TeXstudio:  4.1.1
- Qt:   Using Qt Version 5.12.8, compiled with Qt 5.12.8 R 
- OS:  Linux Mint 20.2 uma .
- TeX distribution: texlive 2021 kpathsea version 6.3.3 

### Expected behavior
 I would expect it to autocomplete and highlight, in green, the name of the \ usepackage {}, as well as the name of \ documentclass {}, (As can be seen in the lower  image)

### Actual behavior
 The packages name is not autocompleted nor recognized by the syntax highlighting green color (most important) they are marked as "not found" when I hover over (As can be seen in the lower second image) https://github.com/texstudio-org/texstudio/issues/1970#issuecomment-981110771.

![1](https://user-images.githubusercontent.com/95192810/143806936-bba39699-c436-4e2c-9320-fe5fa2e71883.jpeg)

![image](https://user-images.githubusercontent.com/95192810/143806984-37d8ac11-055b-40ea-a992-2dbd641fe2dc.png)

It intrigues me that  https://github.com/texstudio-org/texstudio/issues/1970#issuecomment-981110771 we have the same problem in common, only in my case it is on Linux.
I hope that my request is not a bad arrival, I thank, in advance, for the valuable management that is undertaken before my request, best regards.

**Comment by daniel712** [comment] 2021-11-29 14:46
Did you insert these 3 lines in your .profile and logout/login

PATH=/usr/local/texlive/2021/bin/x86_64-linux:$PATH; export PATH
MANPATH=/usr/local/texlive/2021/texmf-dist/doc/man:$MANPATH; export MANPATH
INFOPATH=/usr/local/texlive/2021/texmf-dist/doc/info:$INFOPATH; export INFOPATH

what is the output of:
kpsewhich --show-path ls-R

Also suprises me, that's the other way round on your sys...

**Comment by fdiazruiz** [comment] 2021-11-29 15:50
Dear https://github.com/daniel712, thank you for addressing my problem, you are very kind.

Regarding the texlive installation manual (https://www.tug.org/texmf-dist/doc/texlive/texlive-en/texlive-en.pdf) page 14, this is how you have said it, once installed texlive proceeded to install the lines mentioned in the .profile file (as you can see in the attached image)

On the other hand, the output of kpsewhich --show-path ls-R will also be shown in the attached image.

It really seems very strange to me, but the problem is interesting,
Knowing that there is another person, in this case you, trying to find a possible solution to the same problem, relieves and motivates me. I propose that we exchange as much information as possible to rule out and get the failure and thus solve the problem as soon as possible, best regards.
![1](https://user-images.githubusercontent.com/95192810/143899089-82cf19fa-b489-49fc-b5c6-3b41ea9b91bc.png)
![2](https://user-images.githubusercontent.com/95192810/143899153-2693ed3e-3f1c-41ad-93e6-69ed4e22a6b3.png)

**Comment by daniel712** [comment] 2021-11-29 19:45
So. The Paths and the output of kpsewhich is identical to mine. Except i did put the Paths in /etc/profile.d/zzz.latex.sh - But that makes no difference. And i assume, of course you did logout and login after modifying .profile...

Let's wait for an answer of the developers, where to start further troubleshooting.

Thanks,
  Daniel.

**Comment by fdiazruiz** [comment] 2021-11-30 01:31
Daniel, Following what is cited in that section https://github.com/texstudio-org/texstudio/issues/1970#issuecomment-981455851, I think I was able to solve the problem, I added the packageCache.dat file and the effect of syntax highlighting and autocompletion is appreciated. The question is, what caused the absence of such a file? Greetings..

![image](https://user-images.githubusercontent.com/95192810/143969143-e339232a-9892-47d2-a035-d76c31e698c1.png)

**Comment by daniel712** [comment] 2021-11-30 02:05
Like i mentioned before: Just copying over the file from a working install ist NOT a solution, because the contents of the file do not get updated with this particular texlive install! (Of course you could use this temporally as a "poor mans version" and copy a packageCache.dat file from a FULL texlive install. So you would have all of the tex package names in there for now, whether they are installed actually or not!)

To come back to troubleshooting of the original problem: How did you installed texstudio? Did you install it from the repositories of your distro after the texlive install? Or did you download it from texstudio's website?

In Case you installed it from the repositories you will most probably have a texlive LaTeX install plus additionally a base LaTeX install from the repositories of your MINT distro, because the base system will be installed "normally" as a recommend together with texstudio. So give it a try and remove texstudio (don't forget the config folder) AND all texmf installs of your distro (leave texlive install untouched) and install texstudio with:

sudo apt --no-install-recommends install texstudio texstudio-doc texstudio-l10n

Thanks for the try and your answer! (So we will see, wether the problem is matter of different texmf installed in the system...)
Daniel

**Comment by daniel712** [comment] 2021-11-30 02:16
I just gave it a try on my kubuntu system (VM) and it did NOT solve the problem. I just installed texstudio intentionally together with an additional base latex system next to texlive and the completion and the creation of the PackageCache DID work without problems and has all of the texlive packages in there...

Sorry... let's wait for further investigation by the Pro's... :)

**Comment by daniel712** [comment] 2021-11-30 02:19
Another Idea: Where did you get the packageCache file from? Or did you perhaps just waited now long enough on texlive startup, so it had time to do the parse and fill the cache?

**Comment by fdiazruiz** [comment] 2021-11-30 02:40
That file I extracted from a colleague's computer, but the texstudio he uses is not the current version, I just wanted to test it and make sure it worked. I wanted to ask you a big favor, As his system was able to generate the file of the latest version, I would appreciate it very much if he can share it with me, regards.

**Closed** 2021-11-30 17:10 UTC
