### ISSUE TITLE
Macros menu does not have readable entries

### ISSUE THREAD

**Issue by hannes101** [texstudio-org/texstudio#3533] opened 2024-02-23 20:32 UTC
This is a bug against the beta3, which was just released.
### Environment
- TeXstudio: 4.7.3beta3
- Qt: Using Qt Version 5.15.12, compiled with Qt 5.15.12 R
- OS: fedora 39
- TeX distribution: texlive

### Expected behavior
Entries in the Macro menu are readable in all themes.

### Actual behavior
No matter, which theme is used, there are no entries in the Macro menu. This is with the Classic theme, but the outcome is the same with all themes in the Settings.
Light Theme:
![image](https://github.com/texstudio-org/texstudio/assets/11256578/02b15c5a-d097-4969-91fb-9d93baffa1fb)
Dark Theme:
![image](https://github.com/texstudio-org/texstudio/assets/11256578/eddb55a3-efaa-4047-bc4f-b69cdbd6176e)

### How to reproduce
It's always there.

**Comment by hannes101** [comment] 2024-02-23 20:44
I just noticed that this was already the case with 4.7.2 as well.

**Comment by octaeder** [comment] 2024-02-23 21:26
No issue with win10, current build:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/55831baf-0831-4f41-92cc-60275c980683)

Be aware of the notes in the change log for the current dev and references given there. Especially you may want to backup your macros before testing this dev because macros will change slightly after ending txs dev.

**Comment by muzimuzhi** [comment] 2024-02-23 21:45
I can reproduce the reported problem with TeXstudio 4.7.3beta3, on macOS 13.6.4 (Intel).

![image](https://github.com/texstudio-org/texstudio/assets/6376638/61252a3a-d136-4a30-b44a-aa5bfa06557b)

Click the empty menu item then I get "Uncaught exception at line 1: SyntaxError: Expected token `;'".
![image](https://github.com/texstudio-org/texstudio/assets/6376638/add80d24-f418-4ee2-b0b2-8e77842aae82)

The problem disappears if I delete and then create another macro.

**Comment by octaeder** [comment] 2024-02-23 21:52
can you post the code of the second (unvisible) macro?
How does the 2nd macro looks in 4.7.2?

**Comment by muzimuzhi** [comment] 2024-02-23 22:34
Unfortunately it's already removed. Perhaps it was an unnamed macro with bad body.

Maybe a macro with empty name can be listed in menu with an placeholder, like `<empty name>`.

**Comment by octaeder** [comment] 2024-02-24 03:20
@hannes101 Could you post the file or the json code in the file (`Macro_<n>.txsMacro`) of one of the macros

**Comment by hannes101** [comment] 2024-02-24 06:47
I think I misinterpreted it, but I haven't used Macros as far as I remember. However, then, why not populate the menu only if there are Macros defined?

**Comment by octaeder** [comment] 2024-02-24 13:03
the json code of the macro seeems to be ok. As  you can see the name is empty (`"name": ""`). And there is no macro code (`"tag": [ "" ]`). So this macro will do nothing. I'm a little bit surprised that you were able to save it. Because txs usually removes macros having no name and no code either. To avoid such situations you should always set names for new macros.

**Comment by hannes101** [comment] 2024-02-24 13:10
I actually never used or created macros. So perhaps they are some leftovers, which I carried over in my home directory. This has been moved to new installations for the last couple of years.
So perhaps it was created by ancient versions of Texstudio.

**Comment by sunderme** [comment] 2024-02-24 18:04
so, we can close this ?

**Comment by hannes101** [comment] 2024-02-24 18:14
I am not sure, should we not perhaps check that they are readable before we show empty lines in the menu? Some kind of sanity checks before these are shown?
I also never created these erroneous entries, so not sure how they ended up in there.

**Comment by sunderme** [comment] 2024-02-25 08:10
I close this issue as having empty macros is only cosmetic.
There are no information in here that state that macros are lost. If that can be demonstrated, a new issue is necessary.

**Closed by sunderme** 2024-02-25 08:10 UTC
