### ISSUE TITLE
The whole program blacks out on MacOS

### ISSUE THREAD

**Issue by a-reisberg** [texstudio-org/texstudio#876] opened 2020-01-12 11:10 UTC
### Environment
- TeXstudio: 2.12.18 (downloaded from website)
- Qt:  Qt Version 5.14.0, compiled with Qt 5.14.0 R
- OS: MacOS, Catalina

### Problem
The screen of the whole program becomes gray (or black, depending on whether darkmode is enabled) as if repaint is missed.  This happens randomly, and I cannot find a pattern.  This didn't happen with the previous version of TeXstudio.

**Comment by MeanSquaredError** [comment] 2020-01-14 21:18
Is it still responsive when it comes gray?

**Comment by a-reisberg** [comment] 2020-01-15 09:52
Yes! Everything still works.  For example, if I scroll the editor, it gets painted properly and I can see tex code again (the other parts are still gray).  Same for the pdf viewer/log window.

**Comment by MeanSquaredError** [comment] 2020-01-15 14:57
1. How often does that happen. After 15 minutes of work, after 1 hour of work, after 6 hours?
2. Does it restore the correct look of the whole TXS window if you do minimize/restore or hide/show of the TXS main window?

**Comment by a-reisberg** [comment] 2020-01-15 15:14
1. It happens rather irregularly, and I have not been able to see the pattern.  Sometimes it happens right away.  Sometimes it happens after a while.
2. I have not tried this (I will try this when it happens again and report).  I usually use texstudio in fullscreen mode (of macos).  I've tried moving back and forth between main screen and texstudio's screen.  And this doesn't restore the correct look.

**Comment by MeanSquaredError** [comment] 2020-01-15 22:12
I remember reading something on a web forum about such a problem (missing repaints) with qt+macos+fullscreen. Too bad I am cannot find the exact URL.

Can you please also try to reproduce the problem when you are working in non-fullscreen mode? And also try hide/unhide and minimize/restore of the main TXS window as mentioned in the previous message?

**Comment by a-reisberg** [comment] 2020-01-16 05:53
I probably won't use LaTeX until the weekend.  But I'll try to do what you say then and report back.  Thanks!

**Comment by a-reisberg** [comment] 2020-01-19 16:37
I can confirm now that hide/unhide and minimize/restore of the main TXS window seem to trigger repaint, and so everything is painted correctly after that.

**Comment by MeanSquaredError** [comment] 2020-01-19 17:58
Thank you for the information. Does the problem happen when working in non-fullscreen mode?

**Comment by a-reisberg** [comment] 2020-01-20 07:33
Yes!  What I wrote above for hide/unhide/minimize/restore was for non-fullscreen mode.

I can also try hide/unhide and minimize/restore while in fullscreen mode to see if repaint is triggered in this case and report later.  But I suspect that it's the same.

Thanks!

**Comment by MeanSquaredError** [comment] 2020-01-20 09:29
When you said in the bugreport that "This didn't happen with the previous version of TeXstudio" do you remember which was the last version of TXS that worked correctly? Was it 2.12.16 or an older version?

**Comment by a-reisberg** [comment] 2020-01-20 09:53
It was 2.12.16.

Now, I remember that I upgraded to Catalina (10.15.2) around the time when I switched to TXS 2.12.18.  So it might also be a Catalina problem.  I don't remember if I used 2.12.18 before upgrading to Catalina.

I made a clean macos installation, and the problem still persists with 2.12.18.  I will try again with 2.12.16 and see if I still have this problem.

**Comment by MeanSquaredError** [comment] 2020-01-20 10:27
I suspect that for whatever reason (bug in Qt, bug in TXS itself or bug in MacOS) Qt marks the main window as non-visible (i.e. it sets its `QWidget::visible` to false) or disables updates for the main window (i.e. sets its `QWidget::updatesEnabled` to false). 

When the window is non-visible (or if the updates are disabled) it does not repaint itself when `update()` is called for it. So when you hide/unhide the main window, it resets its `QWidget::visible` flag is from there on it starts working normally.

I would suggest editing the TXS source code and setting up a timer that logs the `visible` and `updatesEnabled` flags to a file. So when it blacks out you can let it run for a few seconds, then hide/unside the main TXS window and then check the contents of the log file.

If the suspicion about `QWidget::visible` is confirmed, then probably it is worth compiling a debug build of TXS, loading it in GDB, setting a write breakpoint on the `QWidget::visible` flag of the main window and then running TXS until it blacks out again and the breakpoint is triggered. Then under GDB it would be possible to look around and see why the main window is marked as non-visible.

If you are comfortable with writing the code to monitor `QWidget::visible` for the main window you can use the new debug logger feature in TXS which simplifies writing debug logs into user-specified text files. It can be enabled when compiling with BUILD.sh or you can enable it by running qmake with DEBUG_LOGGER=true

If you are not comfortable with writing the code to monitor `QWidget::visible`, I can write it too, but it will be a week or so until I will have the time for that.

For the second part (running a debug build of TXS under GDB) you would probably have to try it yourself since I don't have access to macOS at the moment and it seems that none of the other macOS users has reported such an issue.

**Comment by a-reisberg** [comment] 2020-01-21 08:49
I've been testing with 2.12.16 and this issue hasn't appeared.

About your comment, I should add that after the window is grayed out, I can trigger repaint on various components by interacting with them. For example, typing a character or scrolling triggers repaint in the editor (the rest is still grayed out).  Scrolling also makes pdfview and log window repaint. For various buttons, hovering the mouse over them also triggers repaint (but only that particular button is repainted; the rest stays gray). Is this still consistent with your suspicion?

Thanks a lot!

**Comment by MeanSquaredError** [comment] 2020-01-21 10:33
I don't know if your description is consistent with the window being hidden. Maybe my suspicion was incorrect, but then again if the window private data is left in an inconsistent state it could behave almost in any way. Then again, it could be just skipping a repaint event as you suspected initially.

I would speculate that the main window layout has been invalidated but not repainted because at the time of the update event Qt considered it hidden or with disabled updates but without additional information it is difficult to say.

I looked quickly through the commits starting from 2019-05-19 (the release date of TXS 2.12.16) and 2019-12-26 (the release date of TXS 2.12.18) but did not see any obvious code change that would affect the event processing in the main window. Neither did I see why it would skip a repaint event.

At this point if your computer is setup for making custom builds of TXS I would recommend doing a binary search on the commits between these two dates (2019-05-19 and 2019-12-26), picking a commit in the middle building that version of TXS and testing the build whether it has this bug, then repeating the process with half of the interval and so on. I guess it would take 10 attempts or less to pinpoint the first commit from which the buggy behavior appeared.

Then once we know which commit triggers the buggy behavior we could try to figure out what is going on.

**Comment by a-reisberg** [comment] 2020-01-21 12:23
I'll set up my computer to build texstudio as you said (it was set up but I just made a clean install of the OS).  I'll let you know once I figure something out.  My suspicion is that the move from qt 5.12 to 5.14 is the culprit. It will take a bit, since I'm traveling for a couple of weeks.

Thanks a lot for looking into this!

**Comment by MeanSquaredError** [comment] 2020-01-21 13:53
Does TXS on Mac link dynamically to Qt ? Also does the installer ship with its own copies of the Qt libraries or does it use system-wide installation of Qt?

It is possible just to use the new installation of TXS and when running it to tell it to link dynamically against Qt 5.12. If 5.14 is the culprit then the new TXS should not black out when linking dynamically against 5.12.

I would guess that the public Qt API has not changed between 5.12 and 5.14 so such a switch should be possible without rebuilding TXS.

**Comment by a-reisberg** [comment] 2020-01-21 15:55
Good idea!

I think TXS on Mac links dynamically to Qt and that the installer ships its own copies.  By inspecting the TXS package for mac, I see a lot of `dylib` files from Qt. I'll try to replace it with Qt 5.12 from 2.12.16 and see if the problem disappears.

**Comment by a-reisberg** [comment] 2020-01-21 16:06
Actually replacing Qt by hand doesn't work. I get an error saying that TXS wants Qt5.14 but the provided dynamic library is Qt5.12.  I guess I have to build it.

**Comment by a-reisberg** [comment] 2020-02-20 09:22
Finally figured out how to reproduce it (at least 90% of the time).  Somehow, Qt 5.14 has problem with [f.lux](https://justgetflux.com).  During the day or late at night, when f.lux is not manipulating the blue light level, there's no problem.  However, when f.lux manipulates the color, the issue appears.  This can also be seen by manually adjusting the blue light level of the screen in f.lux while txs is running.

**Comment by MeanSquaredError** [comment] 2020-02-20 12:17
Given that you are able to reproduce the problem reliably now, can you please check if the problem indeed is not present with the previous version of TXS (I guess 2.12.16)?

**Comment by a-reisberg** [comment] 2020-02-23 16:51
I can confirm that with 2.12.16, there's no problem.

**Comment by sunderme** [comment] 2020-02-23 17:53
this is probably rather related to Qt5.14/newer xcode sdk

**Comment by a-reisberg** [comment] 2020-02-23 20:57
@sunderme I also thought that this might be a problem with Qt. Is there anything we can do?

**Comment by MeanSquaredError** [comment] 2020-02-23 22:09
flux is a closed-source application, so it is difficult to say what is going on. My guess is that somehow it is messing up the internal state of the TXS main window. Or maybe it sends TXS some weird combination of events that cause it to mess its internal state.

It seems that flux has a setting that disables it just for a certain application. Can you try disabling flux for TXS and see if that makes a difference?

**Comment by MeanSquaredError** [comment] 2020-02-23 22:32
Actually thinking about it, the most straightforward approach to solving it is:
1. Add timer-invoked logging calls TXS in order to find out which internal variable is being messed up for the main TXS window. I suspect `QWidget::visible` or `QWidget::updatesEnabled`, but it could be something else.
2. Once we know which internal variable is messed up, run TXS under a debugger (I think gdb does run under macOS?) and set a write breakpoint on that internal variable of the main TXS window.
3. Once the state of the variable changes, check the call stack and find out which window event and/or method caused this variable change.
4. Then try to come up with some workaround for this.

**Comment by sunderme** [comment] 2020-04-05 07:59
activity on this has ceased ... so

**Closed by sunderme** 2020-04-05 07:59 UTC
