### ISSUE TITLE
SIGSEGV error when deleting using multiple cursors

### ISSUE THREAD

**Issue by davidquarel** [texstudio-org/texstudio#3423] opened 2023-12-15 19:24 UTC
### Environment
- ~TeXstudio 4.2.1 (4.2.1+ds-1)~ TeXstudio 4.7.1 (0.0.0++)
- Qt: 5.15.3
- OS: Kubuntu 22.04.3 LTS
- TeX distribution: pdfTeX 3.141592653-2.6-1.40.22 (TeX Live 2022/dev/Debian)

### Expected behavior

Perform a mass deletion by pressing Ctrl+D a few times on a word to replace to get multiple cursors, and then deleting the target word.

### Actual behavior

'texstudio' terminated by signal SIGSEGV (Address boundary error)

### How to reproduce

1. Open a new file, and fill with the following contents

```
\begin{pmatrix}
    content...
\end{pmatrix}

\begin{pmatrix}
    content...
\end{pmatrix}
```

2. Double-click the first `pmatrix` to highlight it.
3. Press Ctrl+D three times until all instances of `pmatrix` are highlighted.
4. Press `backspace` to attempt to delete the four instances of `pmatrix`.
5. TexStudio crashes.

If texstudio was launched from a terminal, the error 
```
'texstudio' terminated by signal SIGSEGV (Address boundary error)
```
is thrown.

**Comment by davidquarel** [comment] 2023-12-15 19:33
Updated to TeXstudio 4.7.1, and the bug is still present. Below is the backtrace generated.

```
SIGSEGV (TXS-Version 0.0.0++ R )
[bt] /usr/bin/texstudio(_ZN12SimulatedCPU13set_from_realEv+0x45) [0x560f7849c8f9]
[bt] /usr/bin/texstudio(_Z15print_backtraceRK7QString+0x46) [0x560f7849bf0d]
[bt] /usr/bin/texstudio(_ZN9Texstudio16recoverFromCrashEv+0x3cf) [0x560f7835143b]
[bt] /usr/bin/texstudio(_Z7recoverv+0xd) [0x560f78351069]
[bt] /usr/bin/texstudio(_ZNK9QListData4sizeEv+0x13) [0x560f78019757]
[bt] /usr/bin/texstudio(_ZNK5QListI15QDocumentCursorE5countEv+0x1c) [0x560f7818d1ea]
[bt] /usr/bin/texstudio(_ZN7QEditor13keyPressEventEP9QKeyEvent+0x13db) [0x560f783e6d93]
```

**Comment by octaeder** [comment] 2023-12-15 23:20
I could reproduce this sigsev but only once with win10. Not immediately but when I tried to close the editor. The following is from backtrace file:

```
unknown at 7ff62bf9bb92 (TXS-Version 4.7.1-12-gaccfcea45 R )
[bt] 00007ff62bff3c19  q+3481069
[bt] 00007ff62bff2e2b  q+3477503
[bt] 00007ff62bf0c6c7  q+2533531
```
This is from terminal:
```
crashed with signal unknown at 7ff62bf9bb92
unknown at 7ff62bf9bb92 (TXS-Version 4.7.1-12-gaccfcea45 R )
unknown at 7ff62bf9bb92 (TXS-Version 4.7.1-12-gaccfcea45 R )

[bt] 0x7ff62bff3c19  q+3481069

[bt] 0x7ff62bff2e2b  q+3477503

[bt] 0x7ff62bf0c6c7  q+2533531

"C:/msys64/tmp/texstudio_backtrace1.txt"
QString::arg: Argument missing: "INSERT COMMAND: 0:0" , 6
QString::arg: Argument missing: "INSERT COMMAND: 0:0" , 13
QString::arg: Argument missing: "INSERT COMMAND: 6:5" , 7
QString::arg: Argument missing: "INSERT COMMAND: 6:5" , 0
QString::arg: Argument missing: "INSERT COMMAND: 4:7" , 5
QString::arg: Argument missing: "INSERT COMMAND: 4:7" , 0
"Current: 0/3\n0: \nBLOCK:\n    INSERT COMMAND: 0:0\n         Inserted text: \"\\begin{pmatrix}\"\n         Cursor undoOffset: 0   redoOffset: 0\n         Inserted lines:\n         20d689f56e0<ERASED>\n         20d689f5ba0<ERASED>\n         20d689f7230<ERASED>\n         20d689f6ea0<ERASED>\n         20d689f3f20<ERASED>\n         20d689f5e00<ERASED>\n1: \nBLOCK:\n    ERASE COMMAND: 6:5 to 6:-1\n         Erased text: \"pmatrix\", \"\"\n         Cursor undoOffset: 0   redoOffset: 0\n    ERASE COMMAND: 6:5 to 6:-1\n         Erased text: \"}\", \"\"\n         Cursor undoOffset: -1   redoOffset: 0\n    ERASE COMMAND: 4:7 to 4:-1\n         Erased text: \"pmatrix\", \"\"\n         Cursor undoOffset: 0   redoOffset: 0\n2: \nBLOCK:\n    INSERT COMMAND: 6:5\n         Inserted text: \"\"\n         Cursor undoOffset: 0   redoOffset: 0\n         Inserted lines:\n         20d689f42b0<ERASED>\n    INSERT COMMAND: 4:7\n         Inserted text: \"\"\n         Cursor undoOffset: 0   redoOffset: 0\n         Inserted lines:\n         20d689f63f0<ERASED>"
Killed on user request after error: unknown at 7ff62bf9bb92
```

**Comment by sunderme** [comment] 2023-12-16 19:15
the crash should be fixed in the repository

**Closed by sunderme** 2023-12-16 19:15 UTC

**Comment by octaeder** [comment] 2023-12-16 22:02
If it is intended that all for words are deleted, then I must say that this is not the case for me:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/d88e87c1-4e0d-486f-b81c-d8c7e7a95b6f)

Also with full document:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/a409f5f5-ee35-43ec-b055-81f3fceec568)
