### ISSUE TITLE
Magnify tool in PDF viewer disturbes the document with horizontal lines

### ISSUE THREAD

**Issue by marek-zeleny** [texstudio-org/texstudio#1927] opened 2021-11-09 09:32 UTC
### Environment
- TeXstudio: 4.0.4
- Qt: 6.2.1
- OS: Windows 10
- TeX distribution: texlive

### Actual behavior
Magnifying tool in the integrated PDF viewer disturbes the magnified part of the document with horizontal lines (see screenshot).
The lines remain in the previously magnified part of the document afterwards.

![Screenshot 2021-11-09 102220](https://user-images.githubusercontent.com/25250724/140898473-66a83ae0-3d35-4e6c-afa2-0d0d1750fd86.png)

**Comment by muzimuzhi** [comment] 2021-11-09 10:15
duplicate of #1773

short recap: It's a Qt6 bug and is reported. Try the [Qt5 build](https://github.com/texstudio-org/texstudio/releases/tag/4.0.4) instead.

**Comment by marek-zeleny** [comment] 2021-11-09 10:41
Oh, sorry for duplicate, I missed that one (although I did search for it).

The Qt5 build works just fine, thanks.

**Closed** 2021-11-09 10:42 UTC
