### ISSUE TITLE
Files/Windows don't open on MacOS Sonoma 14.1.2

### ISSUE THREAD

**Issue by Srebby** [texstudio-org/texstudio#3405] opened 2023-12-05 14:31 UTC
### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution: 

### Expected behavior
I start up TeXstudio and close the open file and the preview window.

I click on TeXstudio --> preferences
The preferences window should open.

I click on File --> Open Recent --> (select a file)
File should open

I click on File --> Open Recent --> (select a file)
File should open

I click on File --> Open Session -> (select a session)
Files should open
### Actual behavior
In each of the above cases the files do not open.  The main window remains blank.

I tried rebooting the system and it does not make a difference.  Same thing.

### How to reproduce
1. Install TeXstudio
2. Close any files and the preview window.
3. Try to open a file or session.

**Comment by muzimuzhi** [comment] 2023-12-05 14:36
Please try https://github.com/texstudio-org/texstudio/releases/tag/4.7.1rc1.

Duplicate of https://github.com/texstudio-org/texstudio/issues/3395.

**Comment by Srebby** [comment] 2023-12-05 14:36
More information:
If I open the previous version of TeXstudio, open some TeX files, and then close TeXstudio, then...

When I open TeXstudio 4.7.0, those same files open successfully.  If I close all those files and try to reopen them, they do not re-open.

It may or may not be significant, but I am also using Dropbox for my files, and I have it set up so that files are stored in the cloud UNLESS I access them, and then they are permanently stored on my hard-drive.

**Comment by Srebby** [comment] 2023-12-05 14:40
4.7.1rc1 works!

Thanks for the quick response.

David

**Closed** 2023-12-05 16:57 UTC
