### ISSUE TITLE
Magnifying glass cursor not reverting back to normal after magnifying preview

### ISSUE THREAD

**Issue by paulenit** [texstudio-org/texstudio#1069] opened 2020-05-02 07:24 UTC
### Environment
- TeXstudio: _2.12.22_
- Qt: _5.14.2, compiled with Qt 5.14.0 R_
- OS: _Manjaro with Xfce Desktop 4.14_
- TeX distribution: _texlive_

### Expected behavior
When clicking "Build & View (F5)" and hovering and clicking over the preview (internal pdf viewer) the cursor changes to the magnifying glass. When pressing ESC to close the preview panel and getting back to the source code panel the cursor should switch back to default (text editing vertical line).

### Actual behavior
The cursor does not revert and you still have the magnifying glass following you around your text. This does not change upon clicking and selecting text.
!!! Does only happen when clicking in the preview i.e. magnifying the output. !!!

### How to reproduce
Open valid latex document (simple 'article' template is sufficient) and press F5, then click in the preview panel, press ESC and return to the editing panel.

**Comment by sunderme** [comment] 2020-05-02 07:39
seems to be fixed for currentdev builds.
Can you try 3.0.0alpha4 ? (see releases) or build from source ?

**Comment by paulenit** [comment] 2020-05-02 11:51
Downloaded latest AppImage from bintray (texstudio-linux-3.00.00-202004291523-git_e20ec23-x86_64.AppImage) and the bug is still there.

**Comment by MeanSquaredError** [comment] 2020-05-03 08:10
I managed to reproduce the bug. I will try to provide a fix today.

**Comment by MeanSquaredError** [comment] 2020-05-03 09:05
Actually the bug only happens if the user does not move the mouse after releasing the mouse button that caused the zoom. That is:
1. Open the internal PDF viewer.
2. Hover the mouse over some text and press left mouse button (or whichever button causes the magnifying glass to open).
3. Release the mouse button.
4. Without moving the mouse press ESC to close the internal PDF viewer.

Now to find out what exactly is going on in the code...

**Comment by MeanSquaredError** [comment] 2020-05-05 11:03
After some digging into the TXS and Qt source code it seems that this time it is not a TXS bug, but a bug in the Qt itself.

Looks like in some cases when we close the `PDFDocument` widget, Qt does not detect that the widget below the cursor has changed, so it does not bother to refresh the look of the cursor. The bug only shows up when the mouse has not been moved between the mouse button release and ESC keypress. However it has nothing to do with our `PDFWidget::mouseMoveEvent` handler, because it behaves the same way even when I completely remove our `PDFWidget::mouseMoveEvent` handler.

I will try to prepare a workaround that is not too ugly :-)

**Comment by MeanSquaredError** [comment] 2020-05-12 18:04
@sunderme 

After some digging into the code this issue really looks like it is a caused by bug in the Qt code that does showing/hiding of widgets.

I noticed that you upgraded to Qt5.15. Can you please test on your build if the problem still happens with Qt 5.15 ?

That is :
1. Configure TXS to use an embedded internal PDF viewer.
2. Quick build&view a document.
3. In the internal PDF viewer select the zoom tool (it should be selected by default I guess).
4. In the internal PDF viewer left mouseclick the magnifier (zoom tool) on the document text.
5. Release the mouse button to hide the magnifier.
6. Without moving the mouse press the ESC key.

When the bug manifests, the main text editor will get the magnifier tool as a cursor icon.

My idea is that if the bug is fixed in Qt5.15 I can implement an ugly fix and limit it to Qt versions before 5.15.x

**Comment by sunderme** [comment] 2020-05-12 19:27
It is still present with 5.15

**Comment by sunderme** [comment] 2020-05-13 17:12
fixed

**Closed by sunderme** 2020-05-13 17:12 UTC
Labels: bug

**Comment by Oguked** [comment] 2024-09-09 06:03
There error is still there. It's very annoying...

**Comment by octaeder** [comment] 2024-09-09 12:10
can't reproduce with win 10 and latest build
