### ISSUE TITLE
Strange Horizontal Lines are displaying while Magnifiying

### ISSUE THREAD

**Issue by krlogesh** [texstudio-org/texstudio#1966] opened 2021-11-26 16:28 UTC
The Internal PDF error shows some horizontal lines while using the magnification tool
[Error-Texstudio.pdf](https://github.com/texstudio-org/texstudio/files/7609867/Error-Texstudio.pdf)

**Comment by muzimuzhi** [comment] 2021-11-26 16:53
duplicate of #1773

**Comment by krlogesh** [comment] 2021-11-26 17:05
qt5 solves the issue, though the External pdf is throwing flag error while closing the PDF

"Error: unrecognized flag --no-parallel_sweeping Try --help for options"

**Closed** 2021-11-26 18:32 UTC
