### ISSUE TITLE
[Feature Request] Built-in version control system

### ISSUE THREAD

**Issue by TRPrasanna** [texstudio-org/texstudio#1360] opened 2020-11-20 05:51 UTC
It would be great to have a built-in version control system to revert to previous drafts and jump between drafts.

**Comment by flhofer** [comment] 2020-11-20 08:56
TexStudio already "includes" `svn` as a version control system, see File->SVN. I for my part, changed the preferences to use it with git. However, that only works for commit but I do the rest on `zsh` anyway.

Did you try it? Or do you want to be more specific about the feature wish?

**Comment by flhofer** [comment] 2020-11-20 09:05
Duplicate of #911

**Comment by TRPrasanna** [comment] 2020-11-20 09:09
My bad for not looking into this first. I haven't used this before, so I'll comment here once I check it out.

**Comment by sunderme** [comment] 2020-11-25 18:03
support for svn/git has to suffice

**Closed by sunderme** 2020-11-25 18:03 UTC
