### ISSUE TITLE
Compiling texstudio with macosx

### ISSUE THREAD

**Issue by pisabos1705** [texstudio-org/texstudio#2956] opened 2023-02-15 15:01 UTC

**Comment by pisabos1705** [comment] 2023-02-15 15:05
I work with macosx 13.1 and I use texstudio as my latex editor. For my personal needs I have been using   to download the code source of txs to introduce my own  control panels of latex commands. I used to compile txs with the command qmake and everything was going well until Qt 6.4 for which qmake is deprecated.
Now I try to build the application texstudio.app with cmake using the command sh BUILD.sh. However the outcome is that the produced  texstudio application does not work. Double-clicking on icon texstudio.app does not launch this application even if it has been unlocked in Preferences/Security of macosx system.
Therefore I am looking to get in touch with macosx users who compile texstudio using cmake. I would like to know if other users have encountered the same problem and how they solved it.

**Comment by sunderme** [comment] 2023-02-15 16:38
what control panels are you changing.
Some ..._tags.xml ?

**Comment by pisabos1705** [comment] 2023-02-15 17:08
Yes. I add some files into the folder texstudio/tags but also some additions into folders symbols-ng, images-ng and images.  Of course these  additions imply correspondant modifications in some files as texstudio.cpp, symbols.qrc, ....
However, when I download a new release of texstudio I build the application without any modification to test the compilation of this new version.   So when I complain because sh BUILD.sh fails,  this is the source of txs without any modification

**Comment by sunderme** [comment] 2023-02-19 14:31
duplicate of #2947

**Closed by sunderme** 2023-02-19 14:31 UTC
Labels: question
