### ISSUE TITLE
 Mouse cursor will disappear after double click the pdf viewer

### ISSUE THREAD

**Issue by xfdywy** [texstudio-org/texstudio#31] opened 2018-02-05 13:53 UTC
Hello, usually I will double-click the pdf viewer and a magnifying glass will appear. After that, the mouse cursor will disappear. Close the pdf viewer and reopen it will solve this problem. But it is inconvenient.

**Comment by sunderme** [comment] 2018-02-05 17:58
which OS ? which version of txs ?

**Comment by xfdywy** [comment] 2018-02-06 02:07
TeXstudio 2.12.6 (hg 6632:7777b2b8a906)
Using Qt Version 5.9.1, compiled with Qt 5.9.1 R

windows10 version 1709

**Comment by sunderme** [comment] 2018-02-07 17:23
I assume that you are using the windowed pdf viewer from txs ?

**Comment by xfdywy** [comment] 2018-02-08 02:19
Exactly! By the way, I upgrade the txs recently, and the previous version does not have the bug. I can not remember the previous version number exactly.

**Comment by anilyesilkaya** [comment] 2018-03-22 12:50
I am experiencing the exact same problem. My temporary solution is to click on the "Scroll" button (hand icon) in the pdf viewer.

**Comment by CsatiZoltan** [comment] 2018-04-13 14:44
Same issue for me. But it also appears when the Viewer is docked.

TeXstudio 2.12.8 (hg 2.12.8-1-g68cd350)
Using Qt Version 5.8.0, compiled with Qt 5.8.0 R

Windows 7

**Comment by vingt-2** [comment] 2018-06-25 19:33
Same issue here, TeXstudio 2.12.8 (hg 2.12.8-1-g68cd350) on windows 10.

**Comment by hofingermarkus** [comment] 2019-06-02 12:47
Still exists with Windows 10.0.17134 Qt 5.12.1 and TexStudio 2.12.16
However, manually selecting the scroll button as suggested by anilyesilkaya also still works as temporary workaround.

**Comment by jonasstein** [comment] 2019-09-29 09:24
This bug does not show up on Linux. Tested with

```
TeXstudio 2.12.16 (git n/a)
Using Qt Version 5.12.5, compiled with Qt 5.12.3 R
```

Could you please merge the messages in this ticket? I suggest to add `Windows` as `tag`, or in the title.

**Comment by gfroessilva** [comment] 2020-05-14 22:20
Happens to me on: 
TeXstudio 2.12.22 (git 2.12.22)
Using Qt Version 5.12.1, compiled with Qt 5.12.1 R

**Comment by rdecharette** [comment] 2020-06-05 10:38
Same bug for me TeXstudio 2.12.4, Qt Version 5.6.2 (compile Qt 5.6.2 R), Win 10.

My current workaround: ESC (closes the viewer), then F7 (opens it again).

**Comment by ishank-juneja** [comment] 2021-03-09 17:19
Bug still present in Linux variant.

`TeXstudio 2.12.22 (2.12.22+debian-1build1)`

The workaround suggested by @rdecharette is what I am working with for now.

**Comment by JonathanLevine657** [comment] 2021-03-19 17:09
@sunderme 

I found a way to reproduce a similar state using 3.1.2 on linux.

Steps to reproduce:
1. switch to presentation mode (i.e. switch to windowed viewer then hit F5). 
2. double click for magnifier then release mouse button. cursor disappears.
3. exit presentation mode, cursor still missing
4. switch back to embedded viewer, cursor still missing
5. double click magnifier, cursor still missing
6. activate one of the tools from the toolbar, cursor comes back.

Two issues come to mind:
1. The point of presentation mode seems to be always hiding the cursor, but double click still activates the magnifier (whichever tool was active upon entering the mode).  Entering presentation mode forgets the previously active tool and since the active tool isn't restored when presentation mode is exited, hence the bug.
2. Concretely, when exiting presentation mode `PDFDocument::toggleFullScreen` is called:
https://github.com/texstudio-org/texstudio/blob/f6d9e918c74d6600395772fca97273ed658e9b82/src/pdfviewer/PDFDocument.cpp#L3936-L3939
at this point `toolButtonGroup` has no checked button, so `checkedId()` returns -1, which doesn't correspond to any cursor enum. `PDFWidget::setTool` doesn't validate its input and sets the globals to -1, and `PDFWidget::updateCursor` has a switch with no default case, so the invalid value results in no visible cursor.

none of the reporters mentioned presentation mode being needed to trigger this, but this is probably pretty near the mark.

If you set `Preview\EditTool=5` (kPresentation, but really anything except 1 or 2 would behave similarly) in `texstudio.ini`, you get the behavior described all the others. One way to  end up in this state is to enter presentation mode, then exit the program without clicking a tool button.

It might be worth asking the others to report the value of `Preview\EditTool` in their `texstudio.ini` and see what's there.
 

I can't figure out a way to trigger this through the program

**Comment by sunderme** [comment] 2021-03-20 08:39
I think I have found a solution, please check latest version

**Comment by JonathanLevine657** [comment] 2021-03-20 16:50
works for me, but previous reporters described different symptoms to my case - there may be more than one bug. I suggest you confirm with others before closing.

**Comment by JonathanLevine657** [comment] 2021-03-22 19:09
with the new commit, I find that when first starting presentation mode, double clicking for the magnifier and than dragging it, the "scroll" cursor appears in the middle of the magnifier. If you release and try again, it happens again.. If you release and try a third time, no cursor appears.

I don't think the fix addressed the real problems with the code.

**Comment by sunderme** [comment] 2021-03-23 16:27
I don't see anything fault, screencast ?

**Comment by JonathanLevine657** [comment] 2021-03-23 16:48
Could reproduce reliably yesterday, after recompiling, but I can't get it today. I'll see if it pops up again in the next few days.

Different issue: on a multi-page document in presentation mode, can you trigger the magnifier with a double-click without the first click triggering a "next page" action?

**Comment by sunderme** [comment] 2021-03-29 18:11
It seems not to be possible to separate click/double click events. I would actually disable the zoom in presentation mode, if nobody objects.

**Closed** 2021-03-29 18:14 UTC
Labels: bug

**Comment by Remi-Boutin** [comment] 2021-04-29 09:24
Hello,
I have the same issue with the new version of text studio. Let me know if you need more infos. 

OS : Windows 10 

TeXstudio 3.1.1 (git 3.1.1)
Using Qt Version 5.15.2, compiled with Qt 5.15.2 R

**Comment by JonathanLevine657** [comment] 2021-04-29 23:22
@Remi-Boutin, can you check and report the value of `Preview\EditTool=5` in your `texstudio.ini` file? you can find its location with "Help/Check Latex Installation" if you don't know where it is.

**Comment by Remi-Boutin** [comment] 2021-04-30 08:53
Mine is `Preview\EditTool=-1`.

**Comment by sunderme** [comment] 2021-04-30 19:07
try to use 3.1.2beta

**Comment by JonathanLevine657** [comment] 2021-04-30 21:11
Thanks @Remi-Boutin, that's consistent with what I thought triggers this bug. As sunderme said, there's a fix for this already committed, which will be in the next minor version (currently in beta).

**Comment by Remi-Boutin** [comment] 2021-05-05 12:39
The fix seems to do it ! Thanks guys, appreciate it !
