### ISSUE TITLE
Scaling with QT_AUTO_SCREEN_SCALE_FACTOR

### ISSUE THREAD

**Issue by mathsen** [texstudio-org/texstudio#267] opened 2018-08-04 12:35 UTC
### Environment
- TeXstudio:  2.12.10
- Qt:  5.11.1
- OS:  Arch Linux
- TeX distribution:  Texlive

I use a laptop (with high DPI internal display) with a second monitor connected to it (no high DPI).
I have globally set
QT_AUTO_SCREEN_SCALE_FACTOR=1
If I start texstudio and move it on the second screen, icons are way too bit. Changing gui-scaling does not help:
![bug_texstudio](https://user-images.githubusercontent.com/17956971/43676479-99a68354-97f2-11e8-85c0-e92757ef313a.png)

That's how texstudio looks on the first screen:
![texstudio_on_internal_screen](https://user-images.githubusercontent.com/17956971/43676487-d6226604-97f2-11e8-9ba8-4bd018d0fe78.png)

Unsetting QT_AUTO_SCREEN_SCALE_FACTOR solves the issue and texstudio looks as it should on both screens. But unfortunately this brings up other issues with programs that behave correctly with QT_AUTO_SCREEN_SCALE_FACTOR.

**Comment by ddonetskov** [comment] 2019-01-09 13:46
I have a very similar issue with the following setup:
- TeXstudio 2.12.14 (Using Qt Version 5.8.0, compiled with Qt 5.8.0 R),
- Windows 10  (Microsoft Windows [Version 10.0.17134.472]),
- an HDI display with the 175% scaling factor,
- a non-DPI display (96 DPI) with the 100% scaling factor. 

I have configured TeXstudio (with the GUI scaling menu) to look normally on the HDP display. When I move TeXstudion to the non-HDI display, icons are rendered uncomfortably large like on the screenshot above.

Re the QT_AUTO_SCREEN_SCALE_FACTOR setting, I am not sure how to change it on Windows therefore I have not tried it.

The behavior is probably due to the Qt limitation as in handling fractional scaling factors, a solution for it seems to be under development: https://bugreports.qt.io/browse/QTBUG-53022.

I appreciate if someone who understands inners of TeXstudio well would comment on the issue.

**Comment by Doschan** [comment] 2020-10-15 08:43
I have exactly the same issue with:
- TeXstudio 3.0.2 (Using Qt 5.12.3),
- Windows 10.0.19041,
- A two-screens setup with 225% scaling factor and 100% scaling factor.

I haven't been able to solve the problem by setting QT_AUTO_SCREEN_SCALE_FACTOR to 0. However, adding a qt.conf file next to texstudio.exe containing
```
[Platforms]
WindowsArguments = dpiawareness=1
```
fixed partially the problem: now the icons are not too big on the screen with 100% scaling factor, but the text looks badly scaled up. If I set `dpiawareness=0` then everything is fine on the 100% scaling screen but the GUI is a mess on the high-DPI screen...

**Comment by Doschan** [comment] 2020-10-22 13:20
I managed to fix the problem by replacing 
```
#if QT_VERSION >= QT_VERSION_CHECK(5,6,0)
	QApplication::setAttribute(Qt::AA_DisableHighDpiScaling);
#endif
```
in main.cpp by
```
QGuiApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
QGuiApplication::setHighDpiScaleFactorRoundingPolicy(Qt::HighDpiScaleFactorRoundingPolicy::PassThrough);
```
and building with Qt 5.15. Now everything looks great!

**Comment by sunderme** [comment] 2020-10-22 18:05
the reason for the current code is #1042

**Comment by Doschan** [comment] 2020-10-23 07:09
Ah yes you're right, with 
```
QGuiApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
QGuiApplication::setHighDpiScaleFactorRoundingPolicy(Qt::HighDpiScaleFactorRoundingPolicy::PassThrough);
```
the PDF reader and icons look blurry. I didn't notice this because I put texstudio on the main screen...

I tried with only
```
QGuiApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
```
and it looks like it did the job : the pdf reader is fine, and the icons do not overscale when put on a lower-dpi screen. I guess this is quite recent Qt behavior, if it had to be disabled in previous versions...

**Comment by sunderme** [comment] 2020-10-24 09:07
the problem is that there is no clear recommendation how to handle highDPI with Qt and furthermore it seems also be dependent on OS.
So maybe, we need to make it configurable...

**Comment by hungtzuchang** [comment] 2021-02-14 23:53
I had the same problem with Texstudio 3.0.4 on Windows 10 (10.0.19041) with two monitors (267ppi with 200% scaling and 96 ppi with 100% scaling). The problem is fixed by changing the code in main function (main.cpp) to
```
#if QT_VERSION >= QT_VERSION_CHECK(5,6,0)
#ifdef Q_OS_WIN
    QApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
#else
    QApplication::setAttribute(Qt::AA_DisableHighDpiScaling); // the original code
#endif
#endif
```
so the changes are limited to Windows builds (built with MinGW 8.1.0 64-bit/ Qt 5.15.2 on windows).

Looking at the [source code](https://github.com/qt-creator/qt-creator/blob/4.4/src/app/main.cpp) of qtcreator, it seems the line `QApplication::setAttribute(Qt::AA_EnableHighDpiScaling);` has already been there since 2017 (ver. 4.4) but only for Windows...

**Comment by sunderme** [comment] 2021-02-16 15:36
have you looked at the pdf previewer on both monitors. It may be blurry.

**Comment by hungtzuchang** [comment] 2021-02-16 16:50
Here is the screenshot on the high resolution screen
![image](https://user-images.githubusercontent.com/13144197/108092341-78f59180-7031-11eb-8b7f-91fe1a07bb40.png)
and regular screen (the second monitor)
![image](https://user-images.githubusercontent.com/13144197/108092822-ef928f00-7031-11eb-9f47-53f5dd3a8a12.png)
The screenshot for the same pdf file opened by Adobe Reader on the regular screen is shown below
![image](https://user-images.githubusercontent.com/13144197/108093262-6039ab80-7032-11eb-8ff5-5ea3b1d646cb.png)
Although the display quality varies a little between the two screens, the text on both can be read clearly.

[Note] I compiled the code with libpoppler-qt5.dll taken from msys2 rather than an old Texstudio installation. I am not sure whether this makes any difference but just a note here. The steps to compile with libpoppler-qt5.dll from msys2 is shown below:

1. Install mingw-w64-[arch]-poppler and mingw-w64-[arch]-qt5. The libpoppler-qt5.dll file path is /mingw64/bin/libpoppler-qt5-1.dll 
2. Copy the libpoppler-qt5-1.dll to build folder and rename it to libpoppler-qt5.dll
3. Build Texstudio
4. Rename the libpoppler-qt5.dll back to libpoppler-qt5-1.dll
5. Copy all dependent dll's to the build folder

**Comment by sunderme** [comment] 2021-02-16 17:17
okay, implemented

**Comment by sunderme** [comment] 2021-02-19 09:23
again complaints about blurry icons and it messes with adwaita, reverted again.

**Comment by Doschan** [comment] 2021-02-19 10:30
I don't know much about Qt, so I can't do it myself, but it could be great to have it configurable. I don't care about a slightly blurred icon because if I don't put `QGuiApplication::setAttribute(Qt::AA_EnableHighDpiScaling);` I literally cannot use texstudio on my main screen. Maybe by putting an option in settings and reading it at boot ?

**Comment by sunderme** [comment] 2021-02-19 11:33
the settings are only available after that setting needs to be changed ...

**Comment by Doschan** [comment] 2021-02-19 15:23
I see... Then I don't know what could fix the issue. I can keep building my own version with AA_EnableHighDpiScaling, but it is not very convenient. Maybe it will be fixed in Qt6 ?

**Comment by sunderme** [comment] 2021-02-19 16:02
could you live with a command line option, i.e. starting ```texstudio -useqtscaling``` ?

**Comment by sunderme** [comment] 2021-02-19 16:03
I have no idea what qt6 will do on windows. Officially AA_EnableHighDpiScaling should always be enabled ... so , let's see.

**Comment by hungtzuchang** [comment] 2021-02-19 22:40
The EanbleHighDPIScaling could be controlled by environment variables (code below):
```
#if QT_VERSION >= QT_VERSION_CHECK(5,6,0)
#ifdef Q_OS_WIN
    if(!qEnvironmentVariableIsSet("TEXSTUDIO_HIDPI_SCALE")){
        QApplication::setAttribute(Qt::AA_DisableHighDpiScaling);
    }else{
        if(qEnvironmentVariableIntValue("TEXSTUDIO_HIDPI_SCALE")>0)
            QApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
        else
            QApplication::setAttribute(Qt::AA_DisableHighDpiScaling);
    }
#else
    QApplication::setAttribute(Qt::AA_DisableHighDpiScaling);
#endif
#endif
```

Screenshot on regular screen with TEXSTUDIO_HIDPI_SCALE=1
![image](https://user-images.githubusercontent.com/13144197/108568498-04378700-72bf-11eb-8762-37c39a74e0a6.png)
Screenshot on regular screen with TEXSTUDIO_HIDPI_SCALE=0
![image](https://user-images.githubusercontent.com/13144197/108568636-4a8ce600-72bf-11eb-9cf4-1c592c8aafe9.png)
The environment variables on Windows can be set via System Properties dialog and I guess on Linux one can set it easily using shell script

**Comment by sunderme** [comment] 2021-02-20 12:13
that is fine with, implemented 
You can check the latetst dev versions (https://github.com/texstudio-org/texstudio/actions/workflows/cd.yml, click on the top most entry and download of "artifacts" is offered)

**Comment by Doschan** [comment] 2021-02-22 07:39
This is great, thanks!

**Closed** 2024-09-20 19:34 UTC
