### ISSUE TITLE
Store the last setting of the internal pdf viewer.

### ISSUE THREAD

**Issue by EnzoCostantini** [texstudio-org/texstudio#3892] opened 2024-11-29 10:20 UTC
### Describe the feature and the current behavior/state
When viewing a pdf file in the internal viewer, if, for example, you activate the content display on the left-hand side of the window, in order to be able to navigate through the document, this setting does not remain for the next viewing.
### Who will benefit with this feature?
All those who are used to using the content navigator in rather long documents.

**Comment by sunderme** [comment] 2024-11-29 17:18
not sure what exactly is meant here. Screenshots ?

**Comment by EnzoCostantini** [comment] 2024-11-30 12:10
Is it possible to make the content bar always remain visible and not have to display it every time a new file is viewed?
![screenshot](https://github.com/user-attachments/assets/17bd81be-08d9-414b-8afd-c39e4158acdd)

**Comment by octaeder** [comment] 2024-11-30 14:27
For me this seems to be as you wish (win10, msys2 build of current dev).

I tried following:
- switching viewer state between embededded and windowed
- closing and reopening viewer
- ending txs with windowed viewer open or closed
- rebuild currently viewed file
- switch to a different document and choose view document

If you are using a different version or a different OS,  someone else will need to check this. You should take the time to specify the version, OS and a way to reproduce the problem you are describing.

**Comment by sunderme** [comment] 2024-12-08 15:44
issue is not reproducible
pdf window docks are recreated on new windows.

**Closed by sunderme** 2024-12-08 15:44 UTC
