### ISSUE TITLE
Synctex stop working after update

### ISSUE THREAD

**Issue by avnerse** [texstudio-org/texstudio#3279] opened 2023-08-31 13:25 UTC
Hi,
Synctex stopped working for my after updating my TexStudio version from 4.5.2 to 4.6.3.
I checked and the compile command is still
pdflatex.exe -synctex=1 -interaction=nonstopmode %.tex

What happens is that when I press F7 in the editor, the viewer doesn't go to the correct spot in the document (in fact, it remains in the same place) and it stopped responding to CTRL+"Left mouse button" (and doesn't go to the relevant place in the code).

Alas, reinstalling version 4.5.2 didn't fix the problem so it seems like something changed in the configuration and I can't find what.

**Comment by octaeder** [comment] 2023-08-31 13:57
try this https://github.com/texstudio-org/texstudio/issues/3121#issuecomment-1597325589
your OS?

**Comment by avnerse** [comment] 2023-08-31 15:02
Tried both to change the ini file name and to remove the folder and it didn't make any effect on this issue.

I am running a Windows 10.

**Comment by octaeder** [comment] 2023-08-31 15:26
you may also trie the portable versions

**Comment by avnerse** [comment] 2023-09-01 05:59
I have tried to do this with 4.5.2 and that still doesn't fix the problem and it also doesn't work with the portable 4.6.3.
I also tried a full uninstall and install process and that still doesn't work.

**Comment by octaeder** [comment] 2023-09-01 09:48
open cases related to synctex are #2771 and #2681. does one of those fit your problem?
I can't reproduce the error with the latest build.

**Comment by octaeder** [comment] 2023-09-01 12:11
can you update your tex disribution?

**Comment by avnerse** [comment] 2023-09-01 13:24
That's interesting...
#2771 Seems to be related.
The files that I tried to use all had a path with some Hebrew characters in them.
I opened a file with a purely English path and it works.
The other strange thing is that it used to work for me before the update (I actually never noticed that my OneDrive directory has Hebrew in its path as the full path usually doesn't show in the file explorer) and it stopped after the update. It also still works in TexLive.

Also, I have uninstalled and reinstalled MikTex and it doesn't fix the issue with those files.

**Comment by sunderme** [comment] 2023-09-01 16:08
so, duplicate of #2771 ?

**Comment by avnerse** [comment] 2023-09-03 05:37
So it seems

**Closed** 2023-09-04 17:02 UTC
