### ISSUE TITLE
Horizontal Scroll with Trackpad Malfunctioning in Internal PDF Viewer

### ISSUE THREAD

**Issue by YunjiaB** [texstudio-org/texstudio#1272] opened 2020-09-11 18:44 UTC
### Environment
- TeXstudio: 3.0.1
- Qt: 5.15.0 R
- OS: MacOS 10.15.6
- TeX distribution: TeXLive-2020
- Device: MacBook Pro 13-in Early 2015

### Expected behavior
The document in the internal PDF viewer should follow the direction of the trackpad. With the standard gesture used by MacOS, the user can scroll the document with two fingers pressing down and dragging on the trackpad. 

### Actual behavior
The vertical scrolling function works fine, but the horizontal scrolling does not work. In particular, the document always drifts to the left but not to the right. 

### How to reproduce
Zoom in a compiled document in the internal PDF viewer, and scroll with the document with the trackpad.

**Comment by muzimuzhi** [comment] 2020-09-12 07:23
duplicate of #1178

**Closed** 2020-09-12 08:42 UTC
