### ISSUE TITLE
Magnifying glasses don't render the pdf properly 

### ISSUE THREAD

**Issue by alanngh** [texstudio-org/texstudio#2009] opened 2021-12-09 15:57 UTC
the embeded pdf viewer does  not render properly the pdf when you use the magnifying glasses 

### Environment
- TeXstudio:   4.1.2
- Qt:  6.2.1
- OS: windows 11
- TeX distribution: miktext 
### Expected behavior
zoom in the pdf
![Untitled2](https://user-images.githubusercontent.com/31671843/145430440-acdb1c73-8aef-4851-8345-29f2cdf512d7.png)

### Actual behavior
zoom in, but the rendered image is dashed makeing it imposible to see it
![Untitled](https://user-images.githubusercontent.com/31671843/145429683-4626778c-12f0-44a9-8269-ec283e381c71.png)

**Comment by muzimuzhi** [comment] 2021-12-09 16:03
duplicate of #1773

**Closed** 2021-12-09 17:17 UTC
