### ISSUE TITLE
Bug in preview zoom function

### ISSUE THREAD

**Issue by wuliaaa123** [texstudio-org/texstudio#1985] opened 2021-12-01 13:43 UTC
- TeXstudio: 4.1.1
- Qt: 6.2.1 R
- OS: Windows 10
- TeX distribution: ctex

### Expected behavior
When using zoom, the view in zoom is smooth and clear.

### Actual behavior
The view in zoom is mess and there are many lines in the view.
![1](https://user-images.githubusercontent.com/83205242/144245040-35d449ee-8781-487a-a117-aa45e94c6906.png)

**Comment by muzimuzhi** [comment] 2021-12-01 23:43
duplicate of #1773

**Closed** 2021-12-02 20:54 UTC
