### ISSUE TITLE
Begin/end environment not changed simultaneously

### ISSUE THREAD

**Issue by David-Eisenhauer** [texstudio-org/texstudio#2082] opened 2022-01-25 22:40 UTC
With older versions when autocomplete the begin-end-environment, you could write the wanted environment (e.g. Itemize/enumeration) and the end section would be filled simultaneously.

### Environment
- TeXstudio: 4.2.0
- Qt: 5.12.8
- OS: Ubuntu 20.04 LTS
- TeX distribution: TeX Live 2019/Debian

### Expected behavior
End section should be filled simultaneously while begin section will be filled with a value. 

### Actual behavior
End section stays with placeholder instead of changing.

### How to reproduce
Create Begin-end-environment and fill begin section with itemize and try to autocomplete it. End section should stay as it is.

**Comment by muzimuzhi** [comment] 2022-01-26 12:15
Possible duplicate of #2063, hence

> Please try https://github.com/texstudio-org/texstudio/releases/tag/4.2.1beta1

**Comment by David-Eisenhauer** [comment] 2022-01-26 16:33
> Possible duplicate of #2063, hence
> 
> > Please try https://github.com/texstudio-org/texstudio/releases/tag/4.2.1beta1

Thx, this might be. I will try and check if this resolves my issue. The title was not obviously related to my topic... but thanks for notifying!

**Closed** 2022-01-26 20:02 UTC
Labels: duplicate
