### ISSUE TITLE
issue with toggle comment when anchor or cursor are not part of the highlighted lines of a selection

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3147] opened 2023-06-07 15:33 UTC
### Environment
- TeXstudio: 4.5.2, 4.6.0alpha1-31-gde0488c48
- Qt: 6.5.1
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
Toggle Comment should work as it does, when anchor and cursor of the selection are in highlighted lines:
![image](https://github.com/texstudio-org/texstudio/assets/102688820/f2881222-584d-4f7a-ae3a-a8bce5fba228)

### Actual behavior
Make a selection like the following (be aware of the cursor at start of 5th line)
![image](https://github.com/texstudio-org/texstudio/assets/102688820/7c26d1e2-87d5-406d-bc8f-e1b378a84426)
Use twice shortcut `ctrl+t` (or Idefix/Toggle Comment). As the name says there should be no comment. But we see:
![image](https://github.com/texstudio-org/texstudio/assets/102688820/5b8c7c3c-784a-46c9-a8bb-5393eef70bf4)

Or this one (anchor is at start of 4th line where selecting started):
![image](https://github.com/texstudio-org/texstudio/assets/102688820/cf5d3583-6d42-44f7-aa77-72b8a9c04bdd)

This seems to be analog to #3131.

**Comment by sunderme** [comment] 2023-06-08 12:09
for whatever reason, that is intended behavior.
(qeditor.cpp, lines 2779&2780)

**Comment by sunderme** [comment] 2023-06-08 12:17
interestingly VScode behaves the same way => won't fix

**Comment by octaeder** [comment] 2023-06-08 12:26
Ok, so last line not commented or uncommented in some cases. But there is still the problem that is doesn't toggle in all cases and rather continues commenting.

**Comment by sunderme** [comment] 2023-06-08 12:31
okay, I look at it again.

**Closed** 2023-06-08 12:36 UTC

**Comment by octaeder** [comment] 2023-06-08 12:47
thanks
