### ISSUE TITLE
Right brace of `\directlua` is not auto inserted

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#3384] opened 2023-11-24 17:07 UTC
### Environment
- TeXstudio: 4.7.0rc2-1-g9c2e83692
- Qt: 6.6.0
- OS: macOS 13.6.1
- TeX distribution: basicTeX 2023

### Expected behavior

After typing in `\directlua`, continue to type in `{` and get the corresponding right brace `}` automatically inserted.

### Actual behavior

No right brace is inserted and it seems the nearest `}` is used as the corresponding one.

![image](https://github.com/texstudio-org/texstudio/assets/6376638/25172b05-60d0-4b9a-8711-ec78681e9239)

Permanently active `luatex.cwl` and don't use the completion item `\directlua{<lua code>}`, then the problem persists.

### How to reproduce

```tex
\documentclass{article}
\directlua

\begin{document}
content
\end{document}
```

**Comment by sunderme** [comment] 2024-03-16 12:34
There is no (reasonable) solution for this.
The issue is that, when you type `{` , txs looks if a closing brace already exists.
As it switches to lua language context, it does not care about any other opening braces, so it finds `}` from `\begin{document}`.
As it finds a closing brace, it does complete the opening one ...

**Closed by sunderme** 2024-03-16 12:34 UTC
Labels: enhancement
