### ISSUE TITLE
MAC: Crashes when openning a file/section via the TOC

### ISSUE THREAD

**Issue by d3vf1x** [texstudio-org/texstudio#3792] opened 2024-09-11 12:34 UTC
From time to time the textstudio app will crash wehn navigating to a section via the sidbar toc menu.
But it is only a specific section, all other will work fine.
Then after a while this section will also work again.
But once it crashes it will crash consistently, meaning after a restart of the application I can click the same section again and it will crash again.

### Environment
TeXstudio 4.8.2 (git 4.8.2)
Using Qt Version 6.7.2, compiled with Qt 6.7.2 R

Crash report:
https://pastebin.com/r2300x3z

### Expected behavior
Click on the Section should open the corresponding file and jump to the section in it

### Actual behavior
Texstudio will crash. Even after restart the same error will show again.

**Comment by sunderme** [comment] 2024-09-11 16:51
a reproducible test case would be helpful...

**Comment by sunderme** [comment] 2024-09-13 17:24
no way around a test case (or you can debug it yourself)
you can send larger test cases also directly to me (sunderme@gmx.de)

**Comment by d3vf1x** [comment] 2024-09-19 08:02
I cannot find a minimal example that will "reliable" crash...

**Comment by sunderme** [comment] 2024-09-19 16:03
my guess is that the actual bug occurs way before the actual crash.
Are you closing documents before the crash happens ?

**Comment by d3vf1x** [comment] 2024-09-19 16:07
No 100% sure but i would say no.
It is also consistent even after a restart of the program.
When I click on the same section again it will crash again.
But after some time and changes to some files I can click on the same section again and it will not crash...
Thats what it makes so hard to reproduce.
But most of the time i have about 18-12 tabs open.

**Comment by sunderme** [comment] 2024-09-19 19:29
That I don't understand.
When you are at a state that it crashes after a restart. It does not crash the next time ?

**Comment by d3vf1x** [comment] 2024-09-19 19:51
Sorry for any confusion.

It will crash when I click on a particular entry of the Sidebar Window TOC.
Then after a restart I can click on the same Entry and it will crash again.
This can now be repeated indefinitely.

Sometimes it is only on entry that leads to a crash and sometimes there are multiple.

But it is never deterministic (as far as I understand) which entry will lead to a crash.

**Comment by sunderme** [comment] 2024-09-19 19:54
And the crashing document can't be used as a test case ?

**Comment by d3vf1x** [comment] 2024-09-19 19:58
Its a work document i'm not allowed to share unfortunately.
I tried removing any relevant pages to be able to share it but every time I tried this after a crash made the bug disappear.
It seems like altering the content of the pages will "fix" the bug tempoarly.

The funny thing is that I can open the relevant page (the page with the section that will cause the crash) manually without crashing.

**Comment by sunderme** [comment] 2024-09-21 08:56
can you try do disable document caching (options/editor/cache document for faster reopening)

**Comment by d3vf1x** [comment] 2024-09-21 11:11
I deactived it. 
I will give it a try and report how it is going.

**Comment by d3vf1x** [comment] 2024-09-24 21:05
No crashes since then.
This seems to be the "fix"

**Comment by sunderme** [comment] 2024-09-25 17:50
It would be interesting to see what actually causes the crashes.
The "fix" limits its causes but does not really point to something concrete.

**Comment by d3vf1x** [comment] 2024-10-01 17:21
Ok Thank you.
I tried but for some reason I cannot start this build:
![image](https://github.com/user-attachments/assets/bd079260-c398-4e71-a752-6d3946f566cf)

The newest stable release works:
https://github.com/texstudio-org/texstudio/releases/tag/4.8.4

**Comment by sunderme** [comment] 2024-10-01 17:34
build process is the same, no changes there...

**Comment by d3vf1x** [comment] 2024-10-01 18:11
```The application cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x600001aac0f0 {Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}```

**Comment by sunderme** [comment] 2024-10-01 18:45
what binary exactly are we talking about ?

**Comment by sunderme** [comment] 2024-10-01 18:51
on osx emulator, the x86 binary works

**Comment by d3vf1x** [comment] 2024-10-01 19:37
M1
As I said the stable version (M1) works but this build will not launch.
Even though I use the same method (download zip, unzip and start)

**Comment by sunderme** [comment] 2024-10-12 11:44
assume fixed

**Closed by sunderme** 2024-10-12 11:44 UTC

**Comment by ghake** [comment] 2025-03-16 22:09
Problem still present in TeXstudio 4.8.6 m1 installed via homebrew.

---

> Disable document caching (options/editor/cache document for faster reopening)

seems to fix the issue.

**Comment by sunderme** [comment] 2025-03-19 17:44
@d3vf1x @ghake please provide a test case, so that I can fix the issue.
Needed is probably the document set-up.

**Comment by d3vf1x** [comment] 2025-03-19 22:09
@sunderme sure, what do you mean by document setup.
The full project?

**Comment by sunderme** [comment] 2025-03-20 06:11
Yes. It should be simplified to reduce data. That usually already gives a hint what is needed for a crash.

**Comment by sunderme** [comment] 2025-03-20 07:07
You can also send the documents directly to me: sunderme@gmx.de

**Comment by sunderme** [comment] 2025-03-20 07:09
Some info: if caching is involved. That is updated on closing txs and opening documents after a restart of txs.

**Comment by begoodpoussin** [comment] 2025-08-04 19:27
Hi, I have the same crash, using a Macbook m1 with latest version of texstudio 4.8.8. 

What is a test case and how can I provide it?

In my case, when the document cashing is enabled (default) this crash happens in a reproductible way: only when the file the TOC is referring to has not already been open since the main.tex file inputing it was open.

to clarify, the following use cases are described:

1. If the main.tex file is open but the called.tex file the TOC will refer to has not been opened yet, the app will systematically crash.

2. If the main.tex file and the called.tex file the TOC will refer to are open, clicking on the TOC will not crash, put the called.tex in the front, and work properly. 

3. If the main.tex is open, that the called.tex file the TOC will refer to have been open, but is now closed, clicking on the TOC will not crash, open the called.tex file, and work properly. 

4. If the main.tex was open and the TOC working properly, but now the main.tex have been closed and reopened, the TOC will make the app crash until the called.tex file the TOC is referring to has again been opened once since the main.tex was re-opened.

Thank you for your help,

**Comment by sunderme** [comment] 2025-08-05 19:33
In that simplicity, i can't reproduce.
I don't see a crash on intel mac.
