### ISSUE TITLE
Internal viewer's Magnifier generates fictitious thin lines

### ISSUE THREAD

**Issue by sharpcfd** [texstudio-org/texstudio#1906] opened 2021-10-31 03:09 UTC
### Environment
- TeXstudio: 4.0.0 - 4.0.3
- Qt: 6.2.0
- OS: Windows 10
- TeX distribution: miktex

### Actual behavior
The magnifier produces a lot of fictitious thin lines in the view.

See attached pic.
![magnifier](https://user-images.githubusercontent.com/9795251/139565414-ebef5d02-be79-4746-b460-102c8e7eb40c.png)

**Comment by muzimuzhi** [comment] 2021-10-31 05:40
Duplicate of #1773. Does the 4.0.3 Qt5 version work?

**Comment by sharpcfd** [comment] 2021-10-31 06:29
> 
> 
> Duplicate of #1773. Does the 4.0.3 Qt5 version work?

Qt5 has no such problem, but it does not support HDPI.

**Comment by sunderme** [comment] 2021-10-31 08:36
Qt5 supports hidpi. The method is slightly different and it works probably worse if you have several screens with different scaling factors.

**Comment by sunderme** [comment] 2021-10-31 08:37
the issue is coming with 1.25 scaling factor, see link above for work-arounds.

**Closed** 2021-10-31 08:36 UTC
