### ISSUE TITLE
PDF display showing trailing lines after magnifying glass

### ISSUE THREAD

**Issue by Henri-Salha** [texstudio-org/texstudio#1972] opened 2021-11-28 21:43 UTC
After I pass the magnifying glass over a pdf rendering, there are trailing lines. I attach a picture to make this clear. This happens since move to TexStudio 4xxx

### Environment
- TeXstudio: 4.1.
- Qt: Version 6.2.1, compiled with Qt 6.2.1 R
- OS: Windows 10
- TeX distribution: miktex
![texstudio bug](https://user-images.githubusercontent.com/73117230/143787163-03bafbac-8ca1-4870-8482-a932072006f1.jpg)

**Comment by Henri-Salha** [comment] 2021-11-28 21:49
I attach a better picture with comment
![texstudio bug](https://user-images.githubusercontent.com/73117230/143787389-cdf7f3da-32b3-46b3-8686-ae7d98799cf8.jpg)
s

**Comment by muzimuzhi** [comment] 2021-11-28 22:34
maybe duplicate of #1773

**Comment by Henri-Salha** [comment] 2021-11-29 06:10
Indeed it is. Sorry.

**Closed** 2021-11-29 17:38 UTC
Labels: duplicate
