### ISSUE TITLE
\underline gets regarded as a math environment-only command by the editor, but it isn't

### ISSUE THREAD

**Issue by thomas-daniels** [texstudio-org/texstudio#3328] opened 2023-10-12 18:42 UTC
### Environment
- TeXstudio: 4.6.3
- Qt: 6.5.2
- OS: Arch Linux
- TeX distribution: TeX Live

### Expected behavior

The `\underline` command is not marked as red when used outside a math environment and does not show the "math command outside math env" error as tooltip, since the command works perfectly outside math environments. When using autocomplete on `\underline`, dollar signs probably should not automatically be added around it.

### Actual behavior

* When using the `\underline` command outside a math environment, TeXstudio marks it as red with the error "math command outside math env".
* When using autocomplete to input an `\underline` command, TeXstudio automatically adds dollar signs around the command to put it in a math environment.

The document still compiles fine, it's just TeXstudio showing the error in the editor.

### How to reproduce

Type `\underline{something}` in a textual environment and the error marking will immediately appear.

**Comment by sunderme** [comment] 2023-10-12 19:20
do have "plaintex.cwl" manually activated in option/completion ?

**Comment by thomas-daniels** [comment] 2023-10-12 19:27
No, I do not.

Should it be? Pretty sure I never had it manually activated, and it doesn't seem to make a difference if I do.

**Comment by thomas-daniels** [comment] 2023-10-12 19:27
Forgot to add: previous versions did accept \underline fine outside math environments, the current one does not. I do not know since which version exactly this is happening.

**Comment by sunderme** [comment] 2023-10-12 19:28
no, it should not.
by default tex.cwl is active and that has not declared underline as math command, so I can not really reproduce the issue.

**Comment by thomas-daniels** [comment] 2023-10-12 19:32
Thanks for checking. Strange, though, because two friends could just reproduce the issue independently on their machines, with 4.6.3. I doesn't seem like it's just me.

**Comment by sunderme** [comment] 2023-10-12 19:32
okay, looks like that was changed not too long ago, so fixed in dev branch.

**Comment by thomas-daniels** [comment] 2023-10-12 19:32
thanks :)

**Closed by sunderme** 2023-10-12 19:32 UTC
