### ISSUE TITLE
Please test 3.0.0alpha1

### ISSUE THREAD

**Issue by sunderme** [texstudio-org/texstudio#888] opened 2020-01-16 19:35 UTC
Since there have been some fundamental changes on spell checking and syntax highlighting, please test this version.
In case of crashes , backtraces or a description what has been done, would be helpful.

**Comment by foreachthing** [comment] 2020-01-17 05:43
Any chance to get an up-to-date [changelog](https://github.com/texstudio-org/texstudio/blob/master/utilities/manual/CHANGELOG.txt)?
Currently, 2.12.20 is missing... and 3.00.00 has no entries at all. Thanks!

**Comment by sergiokapone** [comment] 2020-01-20 12:45
For  3.0.0alpha1 I found a bubs:
1. Comments inside tikzpicture environment highligted as tikz code (need to be a common comment)
2. tikz-keyword "node" spellchecked.

**Comment by tmelorc** [comment] 2020-01-20 15:54
In Linux Mint 18.
```
TeXstudio 3.00.00 (git n/a)
Using Qt Version 5.7.0, compiled with Qt 5.7.0 D
```

Open Terminal does not work. Nothing happens.

**Comment by paulinsmaier** [comment] 2020-01-23 12:59
Creating a new tex file inside a document, using \input{xyz} and right clicking with: xyz does not exist, should it be created leads to a crash

**Comment by MeanSquaredError** [comment] 2020-01-23 14:30
@paulinsmaier Which platform/OS did you try TXS on?

**Comment by paulinsmaier** [comment] 2020-01-23 14:41
> @paulinsmaier Which platform/OS did you try TXS on?

windows 10, version 1909, Build 18363.535

**Comment by MeanSquaredError** [comment] 2020-01-23 16:35
@paulinsmaier 
Does TXS create any kind of backtrace or crash dump file?

**Comment by paulinsmaier** [comment] 2020-01-23 18:51
> @paulinsmaier
> Does TXS create any kind of backtrace or crash dump file?

It should be called: texstudio_backtrace*.txt, right? Where should it be located? I did a search on all files, but did not find any

**Comment by MeanSquaredError** [comment] 2020-01-24 07:24
@paulinsmaier 
Yes, the backtrace file is called texstudio_backtrace*.txt
TXS uses the "temporary path" for that file for which the programming documentation says "On Windows this is usually the path in the TEMP or TMP environment variable".

So I would check :
1. The `c:\temp` or `c:\tmp` directory if your system has one.
2. Your home directory `c:\users\your_login_name`
3. The TXS appdata directory (same directory where `texstudio.ini` is located)

On a side note, yesterday sunderme committed a bugfix for a somewhat related issue, so maybe you could try the latest windows build and see if it fixes the crash that you observed:

https://bintray.com/sunderme/texstudio/texstudio-win#files
(the latest builds are at the bottom of the page)

**Comment by paulinsmaier** [comment] 2020-01-24 09:11
> On a side note, yesterday sunderme committed a bugfix for a somewhat related issue, so maybe you could try the latest windows build and see if it fixes the crash that you observed:
> 
> https://bintray.com/sunderme/texstudio/texstudio-win#files
> (the latest builds are at the bottom of the page)

Seems fixed in the latest build. Thanks

**Comment by OgreTransporter** [comment] 2020-01-28 16:03
Try to compile latest version (commit e3a4e40f90b942716fd51157929f39e1587533ad).

utilsUI.cpp, line 279: error C2065: "and": undeclared identifier

Either replace `and` with `&&` or include the header `<ciso646>` (http://www.cplusplus.com/reference/ciso646/) which contains the alternative operator representations.

**Comment by tsfg** [comment] 2020-01-28 17:13
Just tested the actual build (texstudio-win-3.00.00-202001272055-git_e3a4e40(zip-Version)) and here are some points I observed:

- I like the progress I see in structure view. It does much better with multi file documets. 
I would even like it more : 

1.  when it will get more like tree showing clearly which file is the root of the actual file and
2.  has a head with summary of labels, TODOs, ... (maybe citations and references) with jumping to the file and position method

- Without loading the glossaries.cwl permanently the new defined (\loadglsentries{}) file wasn't shown in the structural view As well the entry to open the file in the context menu is missing. Having permanently loaded the glossaries.cwl everything was as expected. (didn't test yet for different packages) (The option "load included files" is activated) . 
For References everything is fine.

- When a file is modified and closed without saving, after opening it again (either via structural view or File-open) the changes are still existing and the file is still marked as modified. After a restart of TXS the saved, unmodified state is loaded.

- Is there a change in the handling of LT to enable the online (pro) version ? I could test the online version. Actually, the settings' dialog looks not changed.

**Comment by sergiokapone** [comment] 2020-02-10 07:07
In a dark mode hte button "close" i invisible/ Detais on [video](https://youtu.be/QcGHmaD6a-g)

**Comment by sunderme** [comment] 2020-02-10 19:55
dark mode works best with modern style.
Probably we need to connect both ...

**Comment by bjtho08** [comment] 2020-02-12 10:56
How do I get the Dark Mode option to show up in the configure menu? I downloaded the portable git 3.0.0alpha1 from the Releases tab, but I do not have any Dark Mode option to tick under general>Appearance even with Show Advanced Options enabled.
My OS is Win10.

**Comment by sunderme** [comment] 2020-02-12 14:33
Latest changes are visible in the development version only, see webpage

**Comment by sergiokapone** [comment] 2020-02-12 19:46
I think, the highlighting scheme should be different for the dark and light modes

**Comment by sergiokapone** [comment] 2020-02-13 14:31
After ruturning to light mode, the TXS still reads highlight scheme from [formatsDark]

**Comment by sergiokapone** [comment] 2020-02-14 05:54
Last update TeXstudio 3.00.00 (git 3.0.0alpha1-52-gb124ef0) completely erased both [formats]   and 
[formatsDark]

**Comment by sergiokapone** [comment] 2020-02-14 18:25
Big red button "CLOSE" in Find/Replace dialog is invisible in modern-dark theme

**Comment by sergiokapone** [comment] 2020-02-28 14:02
What happened with window size and position in the latest versions?
[](https://i.imgur.com/RvaOTZL.png)

**Comment by sunderme** [comment] 2020-02-28 14:07
should not be changed

**Comment by sergiokapone** [comment] 2020-02-28 14:29
And yet something happened. The state of the window is not saved after it is closed in maximized mode. (Win10, 1803)

**Comment by MeanSquaredError** [comment] 2020-02-29 00:54
@sergiokapone 
Can you try the following:
1. Before starting TXS save your texstudio.ini (should be in AppData\Roaming\texstudio\texstudio.ini )
2. Start TXS, resize the main window, then exit TXS.
3. Save a second copy of your texstudio.ini
4. Then compare the two saved copies of texstudio.ini and see if they differ.

**Comment by sergiokapone** [comment] 2020-02-29 06:28
My .ini in config\ folder. I use the portable TXS.

Yes, TXS rewrite .ini after closing.
Orig .ini:
`MainWindowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\a\x80\0\0\x3\xb7\0\0\0\x1\0\0\0\x2\0\0\0\x1\0\0\0\x2\xfc\0\0\0\x1\0\0\0\x2\0\0\0\b\0\0\0\f\0\x43\0u\0s\0t\0o\0m\0\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\b\0\x46\0i\0l\0\x65\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\b\0\x45\0\x64\0i\0t\x1\0\0\0\x83\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\n\0T\0o\0o\0l\0s\x1\0\0\x1$\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\b\0M\0\x61\0t\0h\x1\0\0\x1\xc5\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\f\0\x46\0o\0r\0m\0\x61\0t\x1\0\0\x2J\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\n\0T\0\x61\0\x62\0l\0\x65\x1\0\0\x3Y\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\b\0\x44\0i\0\x66\0\x66\0\0\0\x4'\xff\xff\xff\xff\0\0\0\0\0\0\0\0)
MainWindowFullssscreenState=@ByteArray(\0\0\0\xff\0\0\0\x1\xfd\0\0\0\0\0\0\a\x80\0\0\x3\xe4\0\0\0\x1\0\0\0\x2\0\0\0\x1\0\0\0\x2\xfc\0\0\0\x1\0\0\0\x2\0\0\0\b\0\0\0\f\0\x43\0u\0s\0t\0o\0m\0\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\b\0\x46\0i\0l\0\x65\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\b\0\x45\0\x64\0i\0t\x1\0\0\0\x8c\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\n\0T\0o\0o\0l\0s\x1\0\0\x1\x37\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\b\0M\0\x61\0t\0h\x1\0\0\x1\xe2\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\f\0\x46\0o\0r\0m\0\x61\0t\x1\0\0\x2o\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\n\0T\0\x61\0\x62\0l\0\x65\x1\0\0\x3\x88\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\b\0\x44\0i\0\x66\0\x66\0\0\0\x4'\xff\xff\xff\xff\0\0\0\0\0\0\0\0)
MainWindow\Maximized=true
MainWindow\FullScreen=false
Geometries\MainwindowWidth=1920
Geometries\MainwindowHeight=1031
Geometries\MainwindowX=-1
Geometries\MainwindowY=22
`

.ini after closing

`MainWindowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\x5.\0\0\x2\xd0\0\0\0\x1\0\0\0\x2\0\0\0\x1\0\0\0\x2\xfc\0\0\0\x1\0\0\0\x2\0\0\0\b\0\0\0\f\0\x43\0u\0s\0t\0o\0m\0\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\b\0\x46\0i\0l\0\x65\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\b\0\x45\0\x64\0i\0t\x1\0\0\0\x83\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\n\0T\0o\0o\0l\0s\x1\0\0\x1$\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\b\0M\0\x61\0t\0h\x1\0\0\x1\xc5\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\f\0\x46\0o\0r\0m\0\x61\0t\x1\0\0\x2J\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\n\0T\0\x61\0\x62\0l\0\x65\x1\0\0\x3Y\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\b\0\x44\0i\0\x66\0\x66\0\0\0\x4'\xff\xff\xff\xff\0\0\0\0\0\0\0\0)
MainWindowFullssscreenState=@ByteArray(\0\0\0\xff\0\0\0\x1\xfd\0\0\0\0\0\0\a\x80\0\0\x3\xe4\0\0\0\x1\0\0\0\x2\0\0\0\x1\0\0\0\x2\xfc\0\0\0\x1\0\0\0\x2\0\0\0\b\0\0\0\f\0\x43\0u\0s\0t\0o\0m\0\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\b\0\x46\0i\0l\0\x65\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\b\0\x45\0\x64\0i\0t\x1\0\0\0\x8c\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\n\0T\0o\0o\0l\0s\x1\0\0\x1\x37\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\b\0M\0\x61\0t\0h\x1\0\0\x1\xe2\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\f\0\x46\0o\0r\0m\0\x61\0t\x1\0\0\x2o\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\n\0T\0\x61\0\x62\0l\0\x65\x1\0\0\x3\x88\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\b\0\x44\0i\0\x66\0\x66\0\0\0\x4'\xff\xff\xff\xff\0\0\0\0\0\0\0\0)
MainWindow\Maximized=false
MainWindow\FullScreen=false
Geometries\MainwindowWidth=1326
Geometries\MainwindowHeight=800
Geometries\MainwindowX=302
Geometries\MainwindowY=201
`

**Comment by sergiokapone** [comment] 2020-02-29 06:52
Besides, TXS rewrite .ini (Syntax Highlight ) also when I change Dark<->Light mode.  But this has been such a meal for a long time, starting with the first version of alpha.

**Comment by sergiokapone** [comment] 2020-03-12 07:35
In last TeXstudio 3.00.00 (git 3.0.0alpha2-7-gc4bf09a) the problem with minimized window is fixed. Removing SyntaxHighligh sections in the ini are present.

**Comment by ScyllaHide** [comment] 2020-03-22 13:00
### Old Environment
- TeXstudio: 2.12.6 (why are the new binaries so huge?! And well setting up dark theme is very time consuming :/)
- Qt: 5.6.2 
- OS: Windows 10 Build 1903 
- TeX distribution: miktex

### Old Environment (texstudio-win-3.00.00-202003200521-git_ba5d5a7)
- TeXstudio: 3.00.00 (git 3.0.0alpha2-14-gba5d5a7)
- Qt: 5.12.1
- OS: Windows 10 Build 1903 
- TeX distribution: miktex

just tried  and it compiles latex a lot faster compared to 2.12.6, really good job. Also opening of texstudio is a lot faster.

**Since i copied old settings file over from my old version, i assume stuff should work by default?**

But i noticed, that texstudio is launching not in a maximized window, despite the option is set int he ini file. Old open files are not remembered to be opened again ...

wonderful, pdf scrolling is smooth now!!!

i will use this build for some time and if anything goes sideways, i will report it.

**Comment by bonanza123** [comment] 2020-03-28 16:00
Not sure whether I am doing something wrong (I am on archlinux)

```
% chmod +x texstudio-linux-3.00.00-202003280926-git_421482d-x86_64.AppImage 
% ./texstudio-linux-3.00.00-202003280926-git_421482d-x86_64.AppImage       
static QPlatformTheme* QKdeTheme::createKdeTheme(): Unable to determine KDE dirs
```

**Comment by sunderme** [comment] 2020-03-28 17:32
should work

**Comment by sergiokapone** [comment] 2020-03-28 18:12
Minimized window after start is fixed. But erasing Syntax Highlighting afrer dark<->light still there

**Comment by dirkziegenbalg** [comment] 2020-04-03 06:55
First of all: A very nice update. Thanks for the hard work and especially for the dark theme.

I found two points that might be addressed:
1) Spellchecking with languagetool seems to happen on files that are opened during TXS start only when certain paragraphs are changed. Adding a space to the paragraph is sufficient. I would expect that an initial spellcheck is started after opening the file. 
2) When I understand it correctly, the ini-file saves different highlighting settings for the light and dark theme. It would be very nice if one could export and import these settings directly in TXS. This would also help to distribute different flavors of such themes. In the standard dark theme code in commands e.g. \section{Headline} is highlighted with black. At least on my monitors this is almost invisible.

**Comment by sunderme** [comment] 2020-04-04 13:21
use options/save profile, edit out any unwanted information and import on other machine with options/load profile.

**Comment by dirkziegenbalg** [comment] 2020-04-04 18:57
I didn't know that the import can handle partial ini-files. Is this documented somewhere? Nevertheless, this manual way is a bit cumbersome. With respect to usability my first choice would be import and export buttons in the "highlighting-settings-tab" that only handle the editor or IDE style as I know it from various other IDEs.

**Comment by dirkziegenbalg** [comment] 2020-04-04 19:10
okay, I got your point. Maybe someone with more programming skills than me has some spare time 😊

**Comment by sergiokapone** [comment] 2020-04-05 08:39
Sad, but because of the minimized opening it is very inconvenient to use. No corrections are expected

**Comment by update-freak** [comment] 2020-04-12 07:11
I hope that the Dark Design is similar to this one:
https://github.com/texstudio-org/texstudio/issues/45#issuecomment-368334650

**Comment by jrmoserbaltimore** [comment] 2020-05-13 11:38
@sergiokapone is that dark highlighting theme built in or did you have to make it?  I can't find a way to do that; dark mode is just changing my window controls in Alpha 4, not my editor area.

**Comment by jrmoserbaltimore** [comment] 2020-05-13 11:38
I see an x86-64 build for OSX but none for Windows?

**Comment by sergiokapone** [comment] 2020-05-13 15:46
@jrmoserbaltimore dark theme was buit in in a first alpha versions. The 2,3,4th alphas has there are many unwanted features, as for me, so I don't use it. So, may be absence of dark mode is a bew feature of current 4th alpha.

**Comment by sunderme** [comment] 2020-05-13 18:10
?
alpha4 has dark mode support which should be working fine.
The problem is rather what one expects should happen.
1) OS dark mode (e.g. OSX , also KDE): here txs is started with a darker windows colors coming from the OS, syntax highlighting and some icons are adapted by txs. Restart necessary. Unfortunately qt on OSX seems not to work reliable as I see different behavior from CI builds and local builds
2) app dark mode (everywhere): here txs is using a color scheme independent of OS settings. To activate: style = manhattan-dark and ignore most system colors. Restart necessary. Looks okay to me.

**Comment by sergiokapone** [comment] 2020-05-13 18:13
> ?
> alpha4 has dark mode support which should be working fine.
> The problem is rather what one expects should happen.
> 

> 2. app dark mode (everywhere): here txs is using a color scheme independent of OS settings. To activate: style = manhattan-dark and ignore most system colors. Restart necessary. Looks okay to me.

Unfortunately, my txs on Win10_1803 don't think so. I use some earlier build of alpha1, where is ok with dark mode and window maximizing.

**Comment by sergiokapone** [comment] 2020-05-13 18:26
May be for GNU/Linux there are no problems, but for my Win10_1803 bugs do not allow to fully use txs

**Comment by sunderme** [comment] 2020-05-26 18:51
config is rarely changed. You can use the same config for 2.12.22 and 3.0.0*

**Comment by sunderme** [comment] 2020-06-01 11:46
I have added adwaita dark style on windows which seems to be fine.
Please test.

**Comment by jrmoserbaltimore** [comment] 2020-06-01 12:42
I tried compiling the RISC-V specification.  It worked, but the inbuilt preview (from hitting F5 to compile and view) crashed the alpha-4 build.

**Comment by jrmoserbaltimore** [comment] 2020-06-01 12:57
Is there a way to load syntax highlighting profiles so we can get something like @sergiokapone has?

**Comment by sunderme** [comment] 2020-06-01 13:51
> Is there a way to load syntax highlighting profiles so we can get something like @sergiokapone has?

you can use load profile with adapted profiles

**Comment by sunderme** [comment] 2020-06-01 13:52
> I tried compiling the RISC-V specification. It worked, but the inbuilt preview (from hitting F5 to compile and view) crashed the alpha-4 build.

do you have poppler on your system ?

**Comment by sergiokapone** [comment] 2020-06-01 14:06
Will there ever be a fix for minimizing a window at startup?

**Comment by jrmoserbaltimore** [comment] 2020-06-01 16:24
> do you have poppler on your system ?

No, it's Windows.  The previewer works, but not for something that big I'm thinking.

**Comment by MeanSquaredError** [comment] 2020-06-01 20:06
@sergiokapone 
I remember you mentioned that TXS erases parts of your settings. This has not been fixed I guess because the developers were not able to reproduce this problem (at least I was not able to reproduce it).

One thing that I notice in your description is that you use the portable version of TXS. Does the problem with the settings also happen with the non-portable version which is installed in Program Files through an installer ?

**Comment by sergiokapone** [comment] 2020-06-02 16:13
@MeanSquaredError I had tried. Behaviour is the same

**Comment by MeanSquaredError** [comment] 2020-06-03 02:47
@sergiokapone 
I think I managed to reproduce the problem where TXS does not save/restore the maximized state properly under Windows. I will take a look in the next 2-3 days.

**Comment by sergiokapone** [comment] 2020-06-03 10:59
@MeanSquaredError  It would be nice. Also, checking of dark mode in one place would be nice too.

**Comment by jrmoserbaltimore** [comment] 2020-06-03 11:22
It gets in an annoying state where it keeps saying the file changed on disk and asking if you want to reload it or save over it (there are two different dialogues asking about this!), and then does this constantly until you close and relaunch TXS.  This happens for no reason often.

**Comment by sunderme** [comment] 2020-06-03 18:40
> It gets in an annoying state where it keeps saying the file changed on disk and asking if you want to reload it or save over it (there are two different dialogues asking about this!), and then does this constantly until you close and relaunch TXS. This happens for no reason often.

saving on cloud drive (drop box, etc.) ?

**Comment by jrmoserbaltimore** [comment] 2020-06-03 20:42
> saving on cloud drive (drop box, etc.) ?

Nope, local.  It seems to happen constantly and continuously until I restart the program, and then it calms down.

**Comment by sunderme** [comment] 2020-06-03 20:55
> > saving on cloud drive (drop box, etc.) ?
> 
> Nope, local. It seems to happen constantly and continuously until I restart the program, and then it calms down.

Well, that is not normal behavior.
You can open a proper issue report to try to figure it out.

**Comment by sergiokapone** [comment] 2020-06-12 05:52
Why buttons in a search dialog of Adwaita theme abnormally huge?

**Comment by sunderme** [comment] 2020-06-12 07:29
the adwaita style increases the height of the text combobox (search text), the buttons adapt to that

**Comment by sergiokapone** [comment] 2020-06-14 13:41
> the adwaita style increases the height of the text combobox (search text), the buttons adapt to that

Well, you can compare buttons of two comboboxes. The search cocmcobox has bigger buttons then other.
[https://i.imgur.com/WDaF4Zy.jpg](url)

**Closed** 2020-12-29 16:29 UTC
Labels: question
