### ISSUE TITLE
minimum window height is too big on mac since 4.8.0

### ISSUE THREAD

**Issue by val461** [texstudio-org/texstudio#3637] opened 2024-05-13 08:33 UTC
### Environment
- TeXstudio: 4.8.0-osx-m1
- Qt Version 6.7.0, compiled with Qt 6.7.0 R
- OS: Mac M1 14.4.1 (23E224)
- TeX distribution: texlive

### Expected behavior

As with TeXstudio 4.7.3, I should be able to resize the window height to about half the screen.
screencast:
https://jmp.sh/XrTHWxhc
screenshot:
<img width="1440" alt="Screenshot 2024-05-13 at 10 10 42" src="https://github.com/texstudio-org/texstudio/assets/6820182/2dd006af-9ae8-4855-8c25-ec14109ebeac">

### Actual behavior

With the default screen resolution 1440*900, I cannot put the mouse pointer low enough to reach the resize handle. Even activating full screen (by clicking the green button in the top left corner) does not show the full window.

_Edit (2024-05-14): changing the resolution no longer works._

With the screen resolution 1680*1050 on the same computer, I can reduce the height, but not much.
This resolution is less comfortable because text is smaller.

screencast 1440*900:
https://jmp.sh/25D2kktr

screenshot 1440*900:
<img width="1440" alt="Screenshot 2024-05-13 at 09 57 49" src="https://github.com/texstudio-org/texstudio/assets/6820182/5937a6cd-7c4b-480f-bee0-cdcbf54cfe4f">

screencast 1680*1050:
https://jmp.sh/KJXpOVzj

### How to reproduce

Try to reduce window height with the mouse pointer.

### Workaround

On TeXstudio 4.8.1-osx-m1, set Preferences/General/Style to Fusion. Double-click on the window title bar to resize the window.

**Comment by muzimuzhi** [comment] 2024-05-13 08:45
Not reproducible with texstudio 4.8.0 on Intel Mac, macOS 13.6.6.

**Comment by sunderme** [comment] 2024-05-13 10:02
Please execute view/show/reset sidepanel...

**Comment by ZhuZheart98** [comment] 2024-05-13 12:55
this is not working

**Comment by ZhuZheart98** [comment] 2024-05-13 12:58
now I return the version into 4.7.3; https://github.com/texstudio-org/texstudio/releases?page=2. maybe you can do the same thing.

**Comment by val461** [comment] 2024-05-13 13:05
> view/show/reset sidepanel

Done. The issue remains.

**Comment by sunderme** [comment] 2024-05-13 13:35
The dock on the left hand side is still the same ?

**Comment by ZhuZheart98** [comment] 2024-05-13 13:39
this is the same with texstudio 4.8.0 on Intel Mac, macOS 14.4.1

> > view/show/reset sidepanel查看/显示/重置侧面板
> 
> Done. The issue remains.做。问题仍然存在。

**Comment by val461** [comment] 2024-05-13 13:40
> The dock on the left hand side is still the same ?

Yes.

**Comment by sunderme** [comment] 2024-05-13 17:06
the solution is to change options/general/style to anything else but default/osx.
Apparently the OSX style does not allow for scrolling through multiple docks... (unlike all other styles)

**Comment by miss4chewN8** [comment] 2024-05-14 06:22
While this issue remains unsolved, I think one can use the following workaround: Double-click the title bar twice (or once) to get the window resized.

**Comment by val461** [comment] 2024-05-14 11:14
Since my last reboot, the workaround of setting the resolution to 1680*1050 no longer works.

> the solution is to change options/general/style to anything else but default/osx. Apparently the OSX style does not allow for scrolling through multiple docks... (unlike all other styles)

This doesn't work for me.

> Double-click the title bar twice

This does resize the window to a decent height, but causes an other issue: some text on the left overlaps, as on the screenshot below. This other issue applies to the macOS style, but not to the Orion Dark style. With either style, the mouse pointer no longer turns into vertical arrows when trying to resize from the bottom of the window (contrarily to my first post!).
<img width="1440" alt="Screenshot 2024-05-14 at 12 56 13" src="https://github.com/texstudio-org/texstudio/assets/6820182/02f9f0f5-6910-4cdf-99f0-f2e1488e30a9">

**Comment by bishopcranmer** [comment] 2024-05-14 17:51
Perhaps it's helpful to note that one cannot resize from the top with the mouse either. While the mouse pointer will change shape to the left-right mouse pointer on the two vertical sides, it does not change to an up-down pointer at the top, not to a diagonal pointer at the corners.

**Comment by emilywilder** [comment] 2024-05-18 00:24
> the solution is to change options/general/style to anything else but default/osx. Apparently the OSX style does not allow for scrolling through multiple docks... (unlike all other styles)

Can confirm that the window height can be resized and made scrollable in any style other than default/macOS.
I'm using the m1 build of 4.8.0

**Comment by bishopcranmer** [comment] 2024-05-18 07:46
Thank you emilywilder for your feedback. It works just as you say!

**Comment by sunderme** [comment] 2024-05-18 10:44
I have opened a bugreport for qt, let's see (https://bugreports.qt.io/browse/QTBUG-125451)

**Comment by val461** [comment] 2024-05-20 15:03
> the solution is to change options/general/style to anything else but default/osx. Apparently the OSX style does not allow for scrolling through multiple docks... (unlike all other styles)

You can forget I said this doesn't work. I rebooted, tried again, and this works now.

**Comment by bishopcranmer** [comment] 2024-06-05 16:50
I'm using version 4.8.1rc1 and the problem still exists. Every time I open the program, the left column of options are all completely open and one cannot resize the window. The previous session's settings don't "stick".

The quickest solution each time is as follows:
1. Select View -> Show -> Side Panel and turn it "On"
2. Select View -> Show -> Side Panel and turn it "Off"
Then you can resize the window.

**Comment by sunderme** [comment] 2024-06-05 19:32
so, the style is "Fusion" ?
Can you share screenshots ?

**Comment by bishopcranmer** [comment] 2024-06-06 08:44
Screen shot attached. Remember, too, that settings don’t “stick” between sessions. M From: sunderme ***@***.***>Date: Wednesday, June 5, 2024 at 15:32To: texstudio-org/texstudio ***@***.***>Cc: Mark Rudolph ***@***.***>, Comment ***@***.***>Subject: Re: [texstudio-org/texstudio] minimum window height is too big on mac since last update (Issue #3637)so, the style is "Fusion" ?Can you share screenshots ?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by bishopcranmer** [comment] 2024-06-06 12:44
Screen shot follows. Remember, too, that settings don't "stick" between sessions. The setting is for Fusion.
<img width="1454" alt="Screenshot 2024-06-06 at 08 43 33" src="https://github.com/texstudio-org/texstudio/assets/7454272/19f4c889-d52f-4ce2-8dfa-857fd6a102bd">

**Comment by octaeder** [comment] 2024-06-06 13:09
btw. the icon set seems to be inconsistent. Try unchecking

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/8e0e5ac5-87e2-4108-b00b-a70408076cad)

Rest of the image is  just for orientation.

**Comment by bishopcranmer** [comment] 2024-06-06 13:25
I tried unchecking the "Use System Theme Icons" and restarted TexStudio. I still have the same problem, that every time I open the program, the left column of options are all completely open and one cannot resize the window. I must still use the protocol I mentioned above.
The quickest solution each time is as follows:
Select View -> Show -> Side Panel and turn it "On"
Select View -> Show -> Side Panel and turn it "Off"
Then I can resize the window.

<img width="638" alt="Screenshot 2024-06-06 at 09 21 41" src="https://github.com/texstudio-org/texstudio/assets/7454272/999abedf-5682-4db9-963f-ff74ec6c87de">

Thank you for your quick response, by the way!

**Comment by sunderme** [comment] 2024-06-06 19:24
If you close txs while the sidebar is closed (view/show/sidepanel), does it open with the sidepanel closed ?
And if you open the sidepanel then, is it okay ?

**Comment by bishopcranmer** [comment] 2024-06-07 11:45
> If you close txs while the sidebar is closed (view/show/sidepanel), does it open with the sidepanel closed ? And if you open the sidepanel then, is it okay ?

If I close the program with the sidebar closed and then restart the program, the sidebar is again fully open and the window is not resizable. That's what I mean by the setting not "sticking". I have to reset the sidebar each and every time I start the program.

**Comment by sunderme** [comment] 2024-06-07 11:54
Is texstudio.ini in your home/.config/texstudio writable ? What happens if you rename it ?

**Comment by bishopcranmer** [comment] 2024-06-07 14:27
- texstudio.ini renamed to texstudio.ini.old. Restarted TexStudio and got the following (see screen capture).
- I then unchecked `View -> Show -> Side Panel'.
- Closed TexStudio.
- Reopened TexStudio and got exactly the same unresizable screen as in the attached capture.
In other words, the change didn't "stick".
<img width="1375" alt="Screenshot 2024-06-07 at 10 21 45" src="https://github.com/texstudio-org/texstudio/assets/7454272/73e9fb96-79d0-4082-8dab-b22472b4a483">

**Comment by bishopcranmer** [comment] 2024-06-07 14:37
Additional note: after the above steps, I went into settings and changed `Preferences -> General -> Appearance' to what you see in the attached screen capture below. I closed TXS and reopened and I got a resizable window. The settings for the side bar still don't "stick", but at least I don't have to reset the side bar every time to get a resizable window.

This suggests that there's something going on with how the appearance of the side bar is affecting the window as a whole and how its settings aren't being recorded in the INI file?
<img width="538" alt="Screenshot 2024-06-07 at 10 34 55" src="https://github.com/texstudio-org/texstudio/assets/7454272/23ee17e1-4fba-4120-97cf-ac156558845f">

**Comment by val461** [comment] 2024-06-14 09:24
The issue persists with texstudio-4.8.1-osx-m1.

**Comment by sunderme** [comment] 2024-06-15 09:30
Again, I can't reproduce a persistent issue on my computers.
I can only state that the given work-around seems valid.
If that is not the case, we need way more debug information than "does not work".
(exact hardware setup, what was tried, what were the consequences)
Reducing the number of visible docks should definitely help.

**Comment by ansisec** [comment] 2024-06-17 13:08
The problem still exists in the latest version.
Solution:
View->Show->Side Panel (do this 2 or 3 times until the side panel remains closed)
After that, it is possible to resize the window.
After resizing, go to Options -> Save current settings.
You can now close TeXstudio and reopen it

**Comment by val461** [comment] 2024-06-17 13:23
> Again, I can't reproduce a persistent issue on my computers. I can only state that the given work-around seems valid. (https://github.com/texstudio-org/texstudio/wiki/Known-Issues#osx) If that is not the case, we need way more debug information than "does not work". (exact hardware setup, what was tried, what were the consequences) Reducing the number of visible docks should definitely help.

Thank you. Solved for me on 4.8.1-osx-m1, by setting option/general/style to Fusion.

**Comment by miss4chewN8** [comment] 2024-06-18 11:43
> The problem still exists in the latest version. Solution: View->Show->Side Panel (do this 2 or 3 times until the side panel remains closed) After that, it is possible to resize the window. After resizing, go to Options -> Save current settings. You can now close TeXstudio and reopen it

This works perfectly. Thank you!

**Comment by sunderme** [comment] 2024-07-28 09:06
I have build in the work-around measures in the binary. 
If someone still sees this issues, can they test with https://github.com/texstudio-org/texstudio/releases/tag/4.8.2alpha1 ?
It should automatically reset docks and on osx, use fusion style, if and only if, the docks are spread out.

**Comment by ZhuZheart98** [comment] 2024-07-28 09:15
> I have build in the work-around measures in the binary.我在二进制文件中构建了解决方法。 If someone still sees this issues, can they test with [`4.8.2alpha1` (release)](https://github.com/texstudio-org/texstudio/releases/tag/4.8.2alpha1) ?如果有人仍然看到这个问题，他们可以使用 [`4.8.2alpha1`（发布版）](https://github.com/texstudio-org/texstudio/releases/tag/4.8.2alpha1)进行测试吗？ It should automatically reset docks and on osx, use fusion style, if and only if, the docks are spread out.它应该自动重置扩展坞，在 osx 上，使用融合样式，当且仅当扩展坞分散开来。

same problem on Mac(intel). but, it is good if you click the top twice.

**Comment by val461** [comment] 2024-07-28 15:44
> I have build in the work-around measures in the binary. If someone still sees this issues, can they test with https://github.com/texstudio-org/texstudio/releases/tag/4.8.2alpha1 ? It should automatically reset docks and on osx, use fusion style, if and only if, the docks are spread out.

On Mac M1, I set the style back from Fusion to default on 4.8.1, so minimum window height was too big again. I quit Texstudio, then I opened 4.8.2alpha1, and minimum window height was still too big. When I set the style to Fusion, minimum window height is ok, as on 4.8.1.

**Comment by ansisec** [comment] 2024-07-28 16:22
> I have build in the work-around measures in the binary. If someone still sees this issues, can they test with https://github.com/texstudio-org/texstudio/releases/tag/4.8.2alpha1 ? It should automatically reset docks and on osx, use fusion style, if and only if, the docks are spread out.

I've tried this new version on a Mac Pro (Intel), with the default style, and it's working. As it could be that I had a set of settings saved, which solved the problem, I tried deleting them and running with a clean configuration. This also worked without any problems.
THANK YOU VERY MUCH!!!

Having overcome this problem, I'd like to point out another situation I've noticed in recent versions: when you switch between applications with Cmd+Tab, when you go back to texstudio everything seems to freeze, sometimes for about 2 seconds (rendering problem???).

**Comment by sunderme** [comment] 2024-08-22 08:17
4.8.2rc1 does contain an automatism which apllies the workarounds if
1) the dock are spread
2) the screen height is below 900 pixels
Please check if this remedies the issue reported here.

**Comment by ZhuZheart98** [comment] 2024-08-22 08:26
> 4.8.2rc1 does contain an automatism which applies the workarounds if
> 
> 1. the dock are spread
> 2. the screen height is below 900 pixels
>    Please check if this remedies the issue reported here.

this version is ok in Mac Intel 14.5

**Comment by val461** [comment] 2024-08-22 09:46
On Mac M1, I set the style back from Fusion to default on 4.8.2alpha1, so minimum window height was too big again. I quit Texstudio, then I opened 4.8.2rc1, and minimum window height was ok: the style was set to Fusion automatically.

**Comment by sunderme** [comment] 2024-08-22 10:07
Thanks for testing.

**Comment by ansisec** [comment] 2024-08-22 10:43
Just tested a fresh installation of version 4.8.2rc1 on a MacBook Pro Intel running 14.6.1, and it worked without any issues.

**Comment by zhrmdi** [comment] 2024-08-27 08:43
I had the same problem and I confirm with 4.8.2rc1 it works without issues (macOS 12.7.6).

**Comment by sunderme** [comment] 2024-08-30 17:31
fixed with 4.8.2

**Closed by sunderme** 2024-08-30 17:31 UTC

**Comment by rheiland** [comment] 2025-09-30 13:52
Seeing same issue on texstudio-4.9.0alpha1-osx-m1.app . Cannot resize height of window. Cannot even move the window down (partially offscreen) - it snaps back to be very top of screen.  (macOS 15.5, M1 Pro)

FIX: View -> Show -> uncheck "Side panel"
